# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: packages/contracts/proto/policy/v1/policy.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/packages/contracts/proto/policy/v1/policy.proto\x12\x12sysarmor.policy.v1\"\x98\x01\n\x0e\x43onvergeParams\x12\x0c\n\x04mode\x18\x01 \x01(\t\x12\r\n\x05top_k\x18\x02 \x01(\r\x12\x15\n\rmax_path_hops\x18\x03 \x01(\r\x12\x1f\n\x17\x61\x64\x64itive_risk_threshold\x18\x04 \x01(\r\x12\x15\n\rcross_lineage\x18\x05 \x01(\x08\x12\x1a\n\x12state_retention_ns\x18\x06 \x01(\x04\"P\n\x0cRarityParams\x12\x11\n\tcms_width\x18\x01 \x01(\r\x12\x11\n\tcms_depth\x18\x02 \x01(\r\x12\x1a\n\x12\x62\x61seline_window_ns\x18\x03 \x01(\x04\"\xb9\x01\n\x0f\x44\x65tectionPolicy\x12\x16\n\x0e\x65ndpoint_rules\x18\x01 \x03(\t\x12\x13\n\x0b\x63loud_rules\x18\x02 \x03(\t\x12\x34\n\x08\x63onverge\x18\x03 \x01(\x0b\x32\".sysarmor.policy.v1.ConvergeParams\x12\x30\n\x06rarity\x18\x04 \x01(\x0b\x32 .sysarmor.policy.v1.RarityParams\x12\x11\n\tdetectors\x18\x05 \x03(\t\"s\n\x0ePolicyEnvelope\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\x04\x12\x36\n\tdetection\x18\x04 \x01(\x0b\x32#.sysarmor.policy.v1.DetectionPolicyBWZUgithub.com/sysarmor/sysarmor-next-project/packages/contracts/proto/policy/v1;policyv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'packages.contracts.proto.policy.v1.policy_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZUgithub.com/sysarmor/sysarmor-next-project/packages/contracts/proto/policy/v1;policyv1'
  _globals['_CONVERGEPARAMS']._serialized_start=72
  _globals['_CONVERGEPARAMS']._serialized_end=224
  _globals['_RARITYPARAMS']._serialized_start=226
  _globals['_RARITYPARAMS']._serialized_end=306
  _globals['_DETECTIONPOLICY']._serialized_start=309
  _globals['_DETECTIONPOLICY']._serialized_end=494
  _globals['_POLICYENVELOPE']._serialized_start=496
  _globals['_POLICYENVELOPE']._serialized_end=611
# @@protoc_insertion_point(module_scope)
