// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: packages/contracts/proto/dataplane/v1/dataplane.proto

package dataplanev1

import (
	v1 "github.com/sysarmor/sysarmor-next-project/packages/contracts/proto/event/v1"
	v11 "github.com/sysarmor/sysarmor-next-project/packages/contracts/proto/signal/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataAck_Status int32

const (
	DataAck_STATUS_UNSPECIFIED DataAck_Status = 0
	DataAck_STATUS_ACCEPTED    DataAck_Status = 1
	DataAck_STATUS_DUPLICATE   DataAck_Status = 2
	DataAck_STATUS_RETRYABLE   DataAck_Status = 3
	DataAck_STATUS_REJECTED    DataAck_Status = 4
)

// Enum value maps for DataAck_Status.
var (
	DataAck_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_ACCEPTED",
		2: "STATUS_DUPLICATE",
		3: "STATUS_RETRYABLE",
		4: "STATUS_REJECTED",
	}
	DataAck_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_ACCEPTED":    1,
		"STATUS_DUPLICATE":   2,
		"STATUS_RETRYABLE":   3,
		"STATUS_REJECTED":    4,
	}
)

func (x DataAck_Status) Enum() *DataAck_Status {
	p := new(DataAck_Status)
	*p = x
	return p
}

func (x DataAck_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataAck_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_packages_contracts_proto_dataplane_v1_dataplane_proto_enumTypes[0].Descriptor()
}

func (DataAck_Status) Type() protoreflect.EnumType {
	return &file_packages_contracts_proto_dataplane_v1_dataplane_proto_enumTypes[0]
}

func (x DataAck_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataAck_Status.Descriptor instead.
func (DataAck_Status) EnumDescriptor() ([]byte, []int) {
	return file_packages_contracts_proto_dataplane_v1_dataplane_proto_rawDescGZIP(), []int{4, 0}
}

type DataBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *BatchHeader           `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Events        []*EventFrame          `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	Signals       []*SignalFrame         `protobuf:"bytes,3,rep,name=signals,proto3" json:"signals,omitempty"`
	SchemaVersion string                 `protobuf:"bytes,4,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataBatch) Reset() {
	*x = DataBatch{}
	mi := &file_packages_contracts_proto_dataplane_v1_dataplane_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataBatch) ProtoMessage() {}

func (x *DataBatch) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_proto_dataplane_v1_dataplane_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataBatch.ProtoReflect.Descriptor instead.
func (*DataBatch) Descriptor() ([]byte, []int) {
	return file_packages_contracts_proto_dataplane_v1_dataplane_proto_rawDescGZIP(), []int{0}
}

func (x *DataBatch) GetHeader() *BatchHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *DataBatch) GetEvents() []*EventFrame {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *DataBatch) GetSignals() []*SignalFrame {
	if x != nil {
		return x.Signals
	}
	return nil
}

func (x *DataBatch) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

type BatchHeader struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	BatchId            string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	TenantId           string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	AgentId            string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	HostId             string                 `protobuf:"bytes,4,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	PolicyId           string                 `protobuf:"bytes,5,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	PolicyVersion      uint64                 `protobuf:"varint,6,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	PolicyMode         string                 `protobuf:"bytes,7,opt,name=policy_mode,json=policyMode,proto3" json:"policy_mode,omitempty"`
	EventSeqStart      uint64                 `protobuf:"varint,8,opt,name=event_seq_start,json=eventSeqStart,proto3" json:"event_seq_start,omitempty"`
	EventSeqEnd        uint64                 `protobuf:"varint,9,opt,name=event_seq_end,json=eventSeqEnd,proto3" json:"event_seq_end,omitempty"`
	SignalSeqStart     uint64                 `protobuf:"varint,10,opt,name=signal_seq_start,json=signalSeqStart,proto3" json:"signal_seq_start,omitempty"`
	SignalSeqEnd       uint64                 `protobuf:"varint,11,opt,name=signal_seq_end,json=signalSeqEnd,proto3" json:"signal_seq_end,omitempty"`
	EventCount         uint32                 `protobuf:"varint,12,opt,name=event_count,json=eventCount,proto3" json:"event_count,omitempty"`
	SignalCount        uint32                 `protobuf:"varint,13,opt,name=signal_count,json=signalCount,proto3" json:"signal_count,omitempty"`
	DroppedEventsDelta uint64                 `protobuf:"varint,14,opt,name=dropped_events_delta,json=droppedEventsDelta,proto3" json:"dropped_events_delta,omitempty"`
	ParseErrorsDelta   uint64                 `protobuf:"varint,15,opt,name=parse_errors_delta,json=parseErrorsDelta,proto3" json:"parse_errors_delta,omitempty"`
	CreatedAtUnixNano  int64                  `protobuf:"varint,16,opt,name=created_at_unix_nano,json=createdAtUnixNano,proto3" json:"created_at_unix_nano,omitempty"`
	Labels             map[string]string      `protobuf:"bytes,17,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	EnrollmentEpoch    string                 `protobuf:"bytes,18,opt,name=enrollment_epoch,json=enrollmentEpoch,proto3" json:"enrollment_epoch,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BatchHeader) Reset() {
	*x = BatchHeader{}
	mi := &file_packages_contracts_proto_dataplane_v1_dataplane_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchHeader) ProtoMessage() {}

func (x *BatchHeader) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_proto_dataplane_v1_dataplane_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchHeader.ProtoReflect.Descriptor instead.
func (*BatchHeader) Descriptor() ([]byte, []int) {
	return file_packages_contracts_proto_dataplane_v1_dataplane_proto_rawDescGZIP(), []int{1}
}

func (x *BatchHeader) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *BatchHeader) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *BatchHeader) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *BatchHeader) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *BatchHeader) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *BatchHeader) GetPolicyVersion() uint64 {
	if x != nil {
		return x.PolicyVersion
	}
	return 0
}

func (x *BatchHeader) GetPolicyMode() string {
	if x != nil {
		return x.PolicyMode
	}
	return ""
}

func (x *BatchHeader) GetEventSeqStart() uint64 {
	if x != nil {
		return x.EventSeqStart
	}
	return 0
}

func (x *BatchHeader) GetEventSeqEnd() uint64 {
	if x != nil {
		return x.EventSeqEnd
	}
	return 0
}

func (x *BatchHeader) GetSignalSeqStart() uint64 {
	if x != nil {
		return x.SignalSeqStart
	}
	return 0
}

func (x *BatchHeader) GetSignalSeqEnd() uint64 {
	if x != nil {
		return x.SignalSeqEnd
	}
	return 0
}

func (x *BatchHeader) GetEventCount() uint32 {
	if x != nil {
		return x.EventCount
	}
	return 0
}

func (x *BatchHeader) GetSignalCount() uint32 {
	if x != nil {
		return x.SignalCount
	}
	return 0
}

func (x *BatchHeader) GetDroppedEventsDelta() uint64 {
	if x != nil {
		return x.DroppedEventsDelta
	}
	return 0
}

func (x *BatchHeader) GetParseErrorsDelta() uint64 {
	if x != nil {
		return x.ParseErrorsDelta
	}
	return 0
}

func (x *BatchHeader) GetCreatedAtUnixNano() int64 {
	if x != nil {
		return x.CreatedAtUnixNano
	}
	return 0
}

func (x *BatchHeader) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *BatchHeader) GetEnrollmentEpoch() string {
	if x != nil {
		return x.EnrollmentEpoch
	}
	return ""
}

type EventFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	ObservedAt    string                 `protobuf:"bytes,2,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	Event         *v1.CanonicalEvent     `protobuf:"bytes,3,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventFrame) Reset() {
	*x = EventFrame{}
	mi := &file_packages_contracts_proto_dataplane_v1_dataplane_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventFrame) ProtoMessage() {}

func (x *EventFrame) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_proto_dataplane_v1_dataplane_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventFrame.ProtoReflect.Descriptor instead.
func (*EventFrame) Descriptor() ([]byte, []int) {
	return file_packages_contracts_proto_dataplane_v1_dataplane_proto_rawDescGZIP(), []int{2}
}

func (x *EventFrame) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *EventFrame) GetObservedAt() string {
	if x != nil {
		return x.ObservedAt
	}
	return ""
}

func (x *EventFrame) GetEvent() *v1.CanonicalEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type SignalFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	ObservedAt    string                 `protobuf:"bytes,2,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	Signal        *v11.Signal            `protobuf:"bytes,3,opt,name=signal,proto3" json:"signal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalFrame) Reset() {
	*x = SignalFrame{}
	mi := &file_packages_contracts_proto_dataplane_v1_dataplane_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalFrame) ProtoMessage() {}

func (x *SignalFrame) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_proto_dataplane_v1_dataplane_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalFrame.ProtoReflect.Descriptor instead.
func (*SignalFrame) Descriptor() ([]byte, []int) {
	return file_packages_contracts_proto_dataplane_v1_dataplane_proto_rawDescGZIP(), []int{3}
}

func (x *SignalFrame) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *SignalFrame) GetObservedAt() string {
	if x != nil {
		return x.ObservedAt
	}
	return ""
}

func (x *SignalFrame) GetSignal() *v11.Signal {
	if x != nil {
		return x.Signal
	}
	return nil
}

type DataAck struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BatchId         string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	Accepted        bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message         string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Status          DataAck_Status         `protobuf:"varint,4,opt,name=status,proto3,enum=sysarmor.dataplane.v1.DataAck_Status" json:"status,omitempty"`
	ReasonCode      string                 `protobuf:"bytes,5,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	CommittedCursor string                 `protobuf:"bytes,6,opt,name=committed_cursor,json=committedCursor,proto3" json:"committed_cursor,omitempty"`
	ServerTime      string                 `protobuf:"bytes,7,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	AcceptedEvents  uint64                 `protobuf:"varint,8,opt,name=accepted_events,json=acceptedEvents,proto3" json:"accepted_events,omitempty"`
	AcceptedSignals uint64                 `protobuf:"varint,9,opt,name=accepted_signals,json=acceptedSignals,proto3" json:"accepted_signals,omitempty"`
	Retryable       bool                   `protobuf:"varint,10,opt,name=retryable,proto3" json:"retryable,omitempty"`
	RetryAfterMs    uint64                 `protobuf:"varint,11,opt,name=retry_after_ms,json=retryAfterMs,proto3" json:"retry_after_ms,omitempty"`
	Partial         bool                   `protobuf:"varint,12,opt,name=partial,proto3" json:"partial,omitempty"`
	RejectedEvents  uint64                 `protobuf:"varint,13,opt,name=rejected_events,json=rejectedEvents,proto3" json:"rejected_events,omitempty"`
	RejectedSignals uint64                 `protobuf:"varint,14,opt,name=rejected_signals,json=rejectedSignals,proto3" json:"rejected_signals,omitempty"`
	ContractVersion string                 `protobuf:"bytes,15,opt,name=contract_version,json=contractVersion,proto3" json:"contract_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DataAck) Reset() {
	*x = DataAck{}
	mi := &file_packages_contracts_proto_dataplane_v1_dataplane_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataAck) ProtoMessage() {}

func (x *DataAck) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_proto_dataplane_v1_dataplane_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataAck.ProtoReflect.Descriptor instead.
func (*DataAck) Descriptor() ([]byte, []int) {
	return file_packages_contracts_proto_dataplane_v1_dataplane_proto_rawDescGZIP(), []int{4}
}

func (x *DataAck) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *DataAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *DataAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DataAck) GetStatus() DataAck_Status {
	if x != nil {
		return x.Status
	}
	return DataAck_STATUS_UNSPECIFIED
}

func (x *DataAck) GetReasonCode() string {
	if x != nil {
		return x.ReasonCode
	}
	return ""
}

func (x *DataAck) GetCommittedCursor() string {
	if x != nil {
		return x.CommittedCursor
	}
	return ""
}

func (x *DataAck) GetServerTime() string {
	if x != nil {
		return x.ServerTime
	}
	return ""
}

func (x *DataAck) GetAcceptedEvents() uint64 {
	if x != nil {
		return x.AcceptedEvents
	}
	return 0
}

func (x *DataAck) GetAcceptedSignals() uint64 {
	if x != nil {
		return x.AcceptedSignals
	}
	return 0
}

func (x *DataAck) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *DataAck) GetRetryAfterMs() uint64 {
	if x != nil {
		return x.RetryAfterMs
	}
	return 0
}

func (x *DataAck) GetPartial() bool {
	if x != nil {
		return x.Partial
	}
	return false
}

func (x *DataAck) GetRejectedEvents() uint64 {
	if x != nil {
		return x.RejectedEvents
	}
	return 0
}

func (x *DataAck) GetRejectedSignals() uint64 {
	if x != nil {
		return x.RejectedSignals
	}
	return 0
}

func (x *DataAck) GetContractVersion() string {
	if x != nil {
		return x.ContractVersion
	}
	return ""
}

var File_packages_contracts_proto_dataplane_v1_dataplane_proto protoreflect.FileDescriptor

const file_packages_contracts_proto_dataplane_v1_dataplane_proto_rawDesc = "" +
	"\n" +
	"5packages/contracts/proto/dataplane/v1/dataplane.proto\x12\x15sysarmor.dataplane.v1\x1a-packages/contracts/proto/event/v1/event.proto\x1a/packages/contracts/proto/signal/v1/signal.proto\"\xe7\x01\n" +
	"\tDataBatch\x12:\n" +
	"\x06header\x18\x01 \x01(\v2\".sysarmor.dataplane.v1.BatchHeaderR\x06header\x129\n" +
	"\x06events\x18\x02 \x03(\v2!.sysarmor.dataplane.v1.EventFrameR\x06events\x12<\n" +
	"\asignals\x18\x03 \x03(\v2\".sysarmor.dataplane.v1.SignalFrameR\asignals\x12%\n" +
	"\x0eschema_version\x18\x04 \x01(\tR\rschemaVersion\"\xfd\x05\n" +
	"\vBatchHeader\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12\x17\n" +
	"\ahost_id\x18\x04 \x01(\tR\x06hostId\x12\x1b\n" +
	"\tpolicy_id\x18\x05 \x01(\tR\bpolicyId\x12%\n" +
	"\x0epolicy_version\x18\x06 \x01(\x04R\rpolicyVersion\x12\x1f\n" +
	"\vpolicy_mode\x18\a \x01(\tR\n" +
	"policyMode\x12&\n" +
	"\x0fevent_seq_start\x18\b \x01(\x04R\reventSeqStart\x12\"\n" +
	"\revent_seq_end\x18\t \x01(\x04R\veventSeqEnd\x12(\n" +
	"\x10signal_seq_start\x18\n" +
	" \x01(\x04R\x0esignalSeqStart\x12$\n" +
	"\x0esignal_seq_end\x18\v \x01(\x04R\fsignalSeqEnd\x12\x1f\n" +
	"\vevent_count\x18\f \x01(\rR\n" +
	"eventCount\x12!\n" +
	"\fsignal_count\x18\r \x01(\rR\vsignalCount\x120\n" +
	"\x14dropped_events_delta\x18\x0e \x01(\x04R\x12droppedEventsDelta\x12,\n" +
	"\x12parse_errors_delta\x18\x0f \x01(\x04R\x10parseErrorsDelta\x12/\n" +
	"\x14created_at_unix_nano\x18\x10 \x01(\x03R\x11createdAtUnixNano\x12F\n" +
	"\x06labels\x18\x11 \x03(\v2..sysarmor.dataplane.v1.BatchHeader.LabelsEntryR\x06labels\x12)\n" +
	"\x10enrollment_epoch\x18\x12 \x01(\tR\x0fenrollmentEpoch\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x82\x01\n" +
	"\n" +
	"EventFrame\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12\x1f\n" +
	"\vobserved_at\x18\x02 \x01(\tR\n" +
	"observedAt\x127\n" +
	"\x05event\x18\x03 \x01(\v2!.sysarmor.event.v1.CanonicalEventR\x05event\"~\n" +
	"\vSignalFrame\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12\x1f\n" +
	"\vobserved_at\x18\x02 \x01(\tR\n" +
	"observedAt\x122\n" +
	"\x06signal\x18\x03 \x01(\v2\x1a.sysarmor.signal.v1.SignalR\x06signal\"\xaf\x05\n" +
	"\aDataAck\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12=\n" +
	"\x06status\x18\x04 \x01(\x0e2%.sysarmor.dataplane.v1.DataAck.StatusR\x06status\x12\x1f\n" +
	"\vreason_code\x18\x05 \x01(\tR\n" +
	"reasonCode\x12)\n" +
	"\x10committed_cursor\x18\x06 \x01(\tR\x0fcommittedCursor\x12\x1f\n" +
	"\vserver_time\x18\a \x01(\tR\n" +
	"serverTime\x12'\n" +
	"\x0faccepted_events\x18\b \x01(\x04R\x0eacceptedEvents\x12)\n" +
	"\x10accepted_signals\x18\t \x01(\x04R\x0facceptedSignals\x12\x1c\n" +
	"\tretryable\x18\n" +
	" \x01(\bR\tretryable\x12$\n" +
	"\x0eretry_after_ms\x18\v \x01(\x04R\fretryAfterMs\x12\x18\n" +
	"\apartial\x18\f \x01(\bR\apartial\x12'\n" +
	"\x0frejected_events\x18\r \x01(\x04R\x0erejectedEvents\x12)\n" +
	"\x10rejected_signals\x18\x0e \x01(\x04R\x0frejectedSignals\x12)\n" +
	"\x10contract_version\x18\x0f \x01(\tR\x0fcontractVersion\"v\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fSTATUS_ACCEPTED\x10\x01\x12\x14\n" +
	"\x10STATUS_DUPLICATE\x10\x02\x12\x14\n" +
	"\x10STATUS_RETRYABLE\x10\x03\x12\x13\n" +
	"\x0fSTATUS_REJECTED\x10\x042n\n" +
	"\x15AgentDataPlaneService\x12U\n" +
	"\rStreamBatches\x12 .sysarmor.dataplane.v1.DataBatch\x1a\x1e.sysarmor.dataplane.v1.DataAck(\x010\x01B]Z[github.com/sysarmor/sysarmor-next-project/packages/contracts/proto/dataplane/v1;dataplanev1b\x06proto3"

var (
	file_packages_contracts_proto_dataplane_v1_dataplane_proto_rawDescOnce sync.Once
	file_packages_contracts_proto_dataplane_v1_dataplane_proto_rawDescData []byte
)

func file_packages_contracts_proto_dataplane_v1_dataplane_proto_rawDescGZIP() []byte {
	file_packages_contracts_proto_dataplane_v1_dataplane_proto_rawDescOnce.Do(func() {
		file_packages_contracts_proto_dataplane_v1_dataplane_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packages_contracts_proto_dataplane_v1_dataplane_proto_rawDesc), len(file_packages_contracts_proto_dataplane_v1_dataplane_proto_rawDesc)))
	})
	return file_packages_contracts_proto_dataplane_v1_dataplane_proto_rawDescData
}

var file_packages_contracts_proto_dataplane_v1_dataplane_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_packages_contracts_proto_dataplane_v1_dataplane_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_packages_contracts_proto_dataplane_v1_dataplane_proto_goTypes = []any{
	(DataAck_Status)(0),       // 0: sysarmor.dataplane.v1.DataAck.Status
	(*DataBatch)(nil),         // 1: sysarmor.dataplane.v1.DataBatch
	(*BatchHeader)(nil),       // 2: sysarmor.dataplane.v1.BatchHeader
	(*EventFrame)(nil),        // 3: sysarmor.dataplane.v1.EventFrame
	(*SignalFrame)(nil),       // 4: sysarmor.dataplane.v1.SignalFrame
	(*DataAck)(nil),           // 5: sysarmor.dataplane.v1.DataAck
	nil,                       // 6: sysarmor.dataplane.v1.BatchHeader.LabelsEntry
	(*v1.CanonicalEvent)(nil), // 7: sysarmor.event.v1.CanonicalEvent
	(*v11.Signal)(nil),        // 8: sysarmor.signal.v1.Signal
}
var file_packages_contracts_proto_dataplane_v1_dataplane_proto_depIdxs = []int32{
	2, // 0: sysarmor.dataplane.v1.DataBatch.header:type_name -> sysarmor.dataplane.v1.BatchHeader
	3, // 1: sysarmor.dataplane.v1.DataBatch.events:type_name -> sysarmor.dataplane.v1.EventFrame
	4, // 2: sysarmor.dataplane.v1.DataBatch.signals:type_name -> sysarmor.dataplane.v1.SignalFrame
	6, // 3: sysarmor.dataplane.v1.BatchHeader.labels:type_name -> sysarmor.dataplane.v1.BatchHeader.LabelsEntry
	7, // 4: sysarmor.dataplane.v1.EventFrame.event:type_name -> sysarmor.event.v1.CanonicalEvent
	8, // 5: sysarmor.dataplane.v1.SignalFrame.signal:type_name -> sysarmor.signal.v1.Signal
	0, // 6: sysarmor.dataplane.v1.DataAck.status:type_name -> sysarmor.dataplane.v1.DataAck.Status
	1, // 7: sysarmor.dataplane.v1.AgentDataPlaneService.StreamBatches:input_type -> sysarmor.dataplane.v1.DataBatch
	5, // 8: sysarmor.dataplane.v1.AgentDataPlaneService.StreamBatches:output_type -> sysarmor.dataplane.v1.DataAck
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_packages_contracts_proto_dataplane_v1_dataplane_proto_init() }
func file_packages_contracts_proto_dataplane_v1_dataplane_proto_init() {
	if File_packages_contracts_proto_dataplane_v1_dataplane_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packages_contracts_proto_dataplane_v1_dataplane_proto_rawDesc), len(file_packages_contracts_proto_dataplane_v1_dataplane_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_packages_contracts_proto_dataplane_v1_dataplane_proto_goTypes,
		DependencyIndexes: file_packages_contracts_proto_dataplane_v1_dataplane_proto_depIdxs,
		EnumInfos:         file_packages_contracts_proto_dataplane_v1_dataplane_proto_enumTypes,
		MessageInfos:      file_packages_contracts_proto_dataplane_v1_dataplane_proto_msgTypes,
	}.Build()
	File_packages_contracts_proto_dataplane_v1_dataplane_proto = out.File
	file_packages_contracts_proto_dataplane_v1_dataplane_proto_goTypes = nil
	file_packages_contracts_proto_dataplane_v1_dataplane_proto_depIdxs = nil
}
