// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: packages/contracts/proto/streaming/v1/streaming.proto

package streamingv1

import (
	v1 "github.com/sysarmor/sysarmor-next-project/packages/contracts/proto/event/v1"
	v13 "github.com/sysarmor/sysarmor-next-project/packages/contracts/proto/incident/v1"
	v12 "github.com/sysarmor/sysarmor-next-project/packages/contracts/proto/policy/v1"
	v11 "github.com/sysarmor/sysarmor-next-project/packages/contracts/proto/signal/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecordContext struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TenantId           string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	AgentId            string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	HostId             string                 `protobuf:"bytes,3,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	BatchId            string                 `protobuf:"bytes,4,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	PolicyId           string                 `protobuf:"bytes,5,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	PolicyVersion      uint64                 `protobuf:"varint,6,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	PolicyMode         string                 `protobuf:"bytes,7,opt,name=policy_mode,json=policyMode,proto3" json:"policy_mode,omitempty"`
	ObservedAtUnixNano int64                  `protobuf:"varint,8,opt,name=observed_at_unix_nano,json=observedAtUnixNano,proto3" json:"observed_at_unix_nano,omitempty"`
	AnalysisScopeKey   string                 `protobuf:"bytes,9,opt,name=analysis_scope_key,json=analysisScopeKey,proto3" json:"analysis_scope_key,omitempty"`
	Labels             map[string]string      `protobuf:"bytes,10,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RecordContext) Reset() {
	*x = RecordContext{}
	mi := &file_packages_contracts_proto_streaming_v1_streaming_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordContext) ProtoMessage() {}

func (x *RecordContext) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_proto_streaming_v1_streaming_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordContext.ProtoReflect.Descriptor instead.
func (*RecordContext) Descriptor() ([]byte, []int) {
	return file_packages_contracts_proto_streaming_v1_streaming_proto_rawDescGZIP(), []int{0}
}

func (x *RecordContext) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RecordContext) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RecordContext) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *RecordContext) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *RecordContext) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *RecordContext) GetPolicyVersion() uint64 {
	if x != nil {
		return x.PolicyVersion
	}
	return 0
}

func (x *RecordContext) GetPolicyMode() string {
	if x != nil {
		return x.PolicyMode
	}
	return ""
}

func (x *RecordContext) GetObservedAtUnixNano() int64 {
	if x != nil {
		return x.ObservedAtUnixNano
	}
	return 0
}

func (x *RecordContext) GetAnalysisScopeKey() string {
	if x != nil {
		return x.AnalysisScopeKey
	}
	return ""
}

func (x *RecordContext) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type NormalizedTelemetry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion string                 `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Context       *RecordContext         `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*NormalizedTelemetry_Event
	//	*NormalizedTelemetry_Signal
	Payload       isNormalizedTelemetry_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NormalizedTelemetry) Reset() {
	*x = NormalizedTelemetry{}
	mi := &file_packages_contracts_proto_streaming_v1_streaming_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NormalizedTelemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NormalizedTelemetry) ProtoMessage() {}

func (x *NormalizedTelemetry) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_proto_streaming_v1_streaming_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NormalizedTelemetry.ProtoReflect.Descriptor instead.
func (*NormalizedTelemetry) Descriptor() ([]byte, []int) {
	return file_packages_contracts_proto_streaming_v1_streaming_proto_rawDescGZIP(), []int{1}
}

func (x *NormalizedTelemetry) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *NormalizedTelemetry) GetContext() *RecordContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *NormalizedTelemetry) GetPayload() isNormalizedTelemetry_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *NormalizedTelemetry) GetEvent() *v1.CanonicalEvent {
	if x != nil {
		if x, ok := x.Payload.(*NormalizedTelemetry_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *NormalizedTelemetry) GetSignal() *v11.Signal {
	if x != nil {
		if x, ok := x.Payload.(*NormalizedTelemetry_Signal); ok {
			return x.Signal
		}
	}
	return nil
}

type isNormalizedTelemetry_Payload interface {
	isNormalizedTelemetry_Payload()
}

type NormalizedTelemetry_Event struct {
	Event *v1.CanonicalEvent `protobuf:"bytes,3,opt,name=event,proto3,oneof"`
}

type NormalizedTelemetry_Signal struct {
	Signal *v11.Signal `protobuf:"bytes,4,opt,name=signal,proto3,oneof"`
}

func (*NormalizedTelemetry_Event) isNormalizedTelemetry_Payload() {}

func (*NormalizedTelemetry_Signal) isNormalizedTelemetry_Payload() {}

type DetectionPolicySnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion string                 `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	PolicyId      string                 `protobuf:"bytes,3,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	PolicyVersion uint64                 `protobuf:"varint,4,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	Detection     *v12.DetectionPolicy   `protobuf:"bytes,5,opt,name=detection,proto3" json:"detection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectionPolicySnapshot) Reset() {
	*x = DetectionPolicySnapshot{}
	mi := &file_packages_contracts_proto_streaming_v1_streaming_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectionPolicySnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectionPolicySnapshot) ProtoMessage() {}

func (x *DetectionPolicySnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_proto_streaming_v1_streaming_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectionPolicySnapshot.ProtoReflect.Descriptor instead.
func (*DetectionPolicySnapshot) Descriptor() ([]byte, []int) {
	return file_packages_contracts_proto_streaming_v1_streaming_proto_rawDescGZIP(), []int{2}
}

func (x *DetectionPolicySnapshot) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *DetectionPolicySnapshot) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DetectionPolicySnapshot) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *DetectionPolicySnapshot) GetPolicyVersion() uint64 {
	if x != nil {
		return x.PolicyVersion
	}
	return 0
}

func (x *DetectionPolicySnapshot) GetDetection() *v12.DetectionPolicy {
	if x != nil {
		return x.Detection
	}
	return nil
}

type AnalysisArtifact struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion      string                 `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	TenantId           string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	AnalysisScopeKey   string                 `protobuf:"bytes,3,opt,name=analysis_scope_key,json=analysisScopeKey,proto3" json:"analysis_scope_key,omitempty"`
	ObservedAtUnixNano int64                  `protobuf:"varint,4,opt,name=observed_at_unix_nano,json=observedAtUnixNano,proto3" json:"observed_at_unix_nano,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AnalysisArtifact_Signal
	//	*AnalysisArtifact_Incident
	Payload       isAnalysisArtifact_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalysisArtifact) Reset() {
	*x = AnalysisArtifact{}
	mi := &file_packages_contracts_proto_streaming_v1_streaming_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisArtifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisArtifact) ProtoMessage() {}

func (x *AnalysisArtifact) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_proto_streaming_v1_streaming_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisArtifact.ProtoReflect.Descriptor instead.
func (*AnalysisArtifact) Descriptor() ([]byte, []int) {
	return file_packages_contracts_proto_streaming_v1_streaming_proto_rawDescGZIP(), []int{3}
}

func (x *AnalysisArtifact) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *AnalysisArtifact) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *AnalysisArtifact) GetAnalysisScopeKey() string {
	if x != nil {
		return x.AnalysisScopeKey
	}
	return ""
}

func (x *AnalysisArtifact) GetObservedAtUnixNano() int64 {
	if x != nil {
		return x.ObservedAtUnixNano
	}
	return 0
}

func (x *AnalysisArtifact) GetPayload() isAnalysisArtifact_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AnalysisArtifact) GetSignal() *v11.Signal {
	if x != nil {
		if x, ok := x.Payload.(*AnalysisArtifact_Signal); ok {
			return x.Signal
		}
	}
	return nil
}

func (x *AnalysisArtifact) GetIncident() *v13.Incident {
	if x != nil {
		if x, ok := x.Payload.(*AnalysisArtifact_Incident); ok {
			return x.Incident
		}
	}
	return nil
}

type isAnalysisArtifact_Payload interface {
	isAnalysisArtifact_Payload()
}

type AnalysisArtifact_Signal struct {
	Signal *v11.Signal `protobuf:"bytes,5,opt,name=signal,proto3,oneof"`
}

type AnalysisArtifact_Incident struct {
	Incident *v13.Incident `protobuf:"bytes,6,opt,name=incident,proto3,oneof"`
}

func (*AnalysisArtifact_Signal) isAnalysisArtifact_Payload() {}

func (*AnalysisArtifact_Incident) isAnalysisArtifact_Payload() {}

type RejectedTelemetry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion string                 `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	BatchId       string                 `protobuf:"bytes,4,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	ReasonCode    string                 `protobuf:"bytes,5,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectedTelemetry) Reset() {
	*x = RejectedTelemetry{}
	mi := &file_packages_contracts_proto_streaming_v1_streaming_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectedTelemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectedTelemetry) ProtoMessage() {}

func (x *RejectedTelemetry) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_proto_streaming_v1_streaming_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectedTelemetry.ProtoReflect.Descriptor instead.
func (*RejectedTelemetry) Descriptor() ([]byte, []int) {
	return file_packages_contracts_proto_streaming_v1_streaming_proto_rawDescGZIP(), []int{4}
}

func (x *RejectedTelemetry) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *RejectedTelemetry) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RejectedTelemetry) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RejectedTelemetry) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *RejectedTelemetry) GetReasonCode() string {
	if x != nil {
		return x.ReasonCode
	}
	return ""
}

func (x *RejectedTelemetry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LateTelemetry struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Telemetry         *NormalizedTelemetry   `protobuf:"bytes,1,opt,name=telemetry,proto3" json:"telemetry,omitempty"`
	WatermarkUnixNano int64                  `protobuf:"varint,2,opt,name=watermark_unix_nano,json=watermarkUnixNano,proto3" json:"watermark_unix_nano,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LateTelemetry) Reset() {
	*x = LateTelemetry{}
	mi := &file_packages_contracts_proto_streaming_v1_streaming_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LateTelemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LateTelemetry) ProtoMessage() {}

func (x *LateTelemetry) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_proto_streaming_v1_streaming_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LateTelemetry.ProtoReflect.Descriptor instead.
func (*LateTelemetry) Descriptor() ([]byte, []int) {
	return file_packages_contracts_proto_streaming_v1_streaming_proto_rawDescGZIP(), []int{5}
}

func (x *LateTelemetry) GetTelemetry() *NormalizedTelemetry {
	if x != nil {
		return x.Telemetry
	}
	return nil
}

func (x *LateTelemetry) GetWatermarkUnixNano() int64 {
	if x != nil {
		return x.WatermarkUnixNano
	}
	return 0
}

var File_packages_contracts_proto_streaming_v1_streaming_proto protoreflect.FileDescriptor

const file_packages_contracts_proto_streaming_v1_streaming_proto_rawDesc = "" +
	"\n" +
	"5packages/contracts/proto/streaming/v1/streaming.proto\x12\x15sysarmor.streaming.v1\x1a-packages/contracts/proto/event/v1/event.proto\x1a3packages/contracts/proto/incident/v1/incident.proto\x1a/packages/contracts/proto/policy/v1/policy.proto\x1a/packages/contracts/proto/signal/v1/signal.proto\"\xc6\x03\n" +
	"\rRecordContext\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x17\n" +
	"\ahost_id\x18\x03 \x01(\tR\x06hostId\x12\x19\n" +
	"\bbatch_id\x18\x04 \x01(\tR\abatchId\x12\x1b\n" +
	"\tpolicy_id\x18\x05 \x01(\tR\bpolicyId\x12%\n" +
	"\x0epolicy_version\x18\x06 \x01(\x04R\rpolicyVersion\x12\x1f\n" +
	"\vpolicy_mode\x18\a \x01(\tR\n" +
	"policyMode\x121\n" +
	"\x15observed_at_unix_nano\x18\b \x01(\x03R\x12observedAtUnixNano\x12,\n" +
	"\x12analysis_scope_key\x18\t \x01(\tR\x10analysisScopeKey\x12H\n" +
	"\x06labels\x18\n" +
	" \x03(\v20.sysarmor.streaming.v1.RecordContext.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf8\x01\n" +
	"\x13NormalizedTelemetry\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\tR\rschemaVersion\x12>\n" +
	"\acontext\x18\x02 \x01(\v2$.sysarmor.streaming.v1.RecordContextR\acontext\x129\n" +
	"\x05event\x18\x03 \x01(\v2!.sysarmor.event.v1.CanonicalEventH\x00R\x05event\x124\n" +
	"\x06signal\x18\x04 \x01(\v2\x1a.sysarmor.signal.v1.SignalH\x00R\x06signalB\t\n" +
	"\apayload\"\xe4\x01\n" +
	"\x17DetectionPolicySnapshot\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\tR\rschemaVersion\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1b\n" +
	"\tpolicy_id\x18\x03 \x01(\tR\bpolicyId\x12%\n" +
	"\x0epolicy_version\x18\x04 \x01(\x04R\rpolicyVersion\x12A\n" +
	"\tdetection\x18\x05 \x01(\v2#.sysarmor.policy.v1.DetectionPolicyR\tdetection\"\xb6\x02\n" +
	"\x10AnalysisArtifact\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\tR\rschemaVersion\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12,\n" +
	"\x12analysis_scope_key\x18\x03 \x01(\tR\x10analysisScopeKey\x121\n" +
	"\x15observed_at_unix_nano\x18\x04 \x01(\x03R\x12observedAtUnixNano\x124\n" +
	"\x06signal\x18\x05 \x01(\v2\x1a.sysarmor.signal.v1.SignalH\x00R\x06signal\x12<\n" +
	"\bincident\x18\x06 \x01(\v2\x1e.sysarmor.incident.v1.IncidentH\x00R\bincidentB\t\n" +
	"\apayload\"\xc8\x01\n" +
	"\x11RejectedTelemetry\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\tR\rschemaVersion\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12\x19\n" +
	"\bbatch_id\x18\x04 \x01(\tR\abatchId\x12\x1f\n" +
	"\vreason_code\x18\x05 \x01(\tR\n" +
	"reasonCode\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\"\x89\x01\n" +
	"\rLateTelemetry\x12H\n" +
	"\ttelemetry\x18\x01 \x01(\v2*.sysarmor.streaming.v1.NormalizedTelemetryR\ttelemetry\x12.\n" +
	"\x13watermark_unix_nano\x18\x02 \x01(\x03R\x11watermarkUnixNanoB]Z[github.com/sysarmor/sysarmor-next-project/packages/contracts/proto/streaming/v1;streamingv1b\x06proto3"

var (
	file_packages_contracts_proto_streaming_v1_streaming_proto_rawDescOnce sync.Once
	file_packages_contracts_proto_streaming_v1_streaming_proto_rawDescData []byte
)

func file_packages_contracts_proto_streaming_v1_streaming_proto_rawDescGZIP() []byte {
	file_packages_contracts_proto_streaming_v1_streaming_proto_rawDescOnce.Do(func() {
		file_packages_contracts_proto_streaming_v1_streaming_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packages_contracts_proto_streaming_v1_streaming_proto_rawDesc), len(file_packages_contracts_proto_streaming_v1_streaming_proto_rawDesc)))
	})
	return file_packages_contracts_proto_streaming_v1_streaming_proto_rawDescData
}

var file_packages_contracts_proto_streaming_v1_streaming_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_packages_contracts_proto_streaming_v1_streaming_proto_goTypes = []any{
	(*RecordContext)(nil),           // 0: sysarmor.streaming.v1.RecordContext
	(*NormalizedTelemetry)(nil),     // 1: sysarmor.streaming.v1.NormalizedTelemetry
	(*DetectionPolicySnapshot)(nil), // 2: sysarmor.streaming.v1.DetectionPolicySnapshot
	(*AnalysisArtifact)(nil),        // 3: sysarmor.streaming.v1.AnalysisArtifact
	(*RejectedTelemetry)(nil),       // 4: sysarmor.streaming.v1.RejectedTelemetry
	(*LateTelemetry)(nil),           // 5: sysarmor.streaming.v1.LateTelemetry
	nil,                             // 6: sysarmor.streaming.v1.RecordContext.LabelsEntry
	(*v1.CanonicalEvent)(nil),       // 7: sysarmor.event.v1.CanonicalEvent
	(*v11.Signal)(nil),              // 8: sysarmor.signal.v1.Signal
	(*v12.DetectionPolicy)(nil),     // 9: sysarmor.policy.v1.DetectionPolicy
	(*v13.Incident)(nil),            // 10: sysarmor.incident.v1.Incident
}
var file_packages_contracts_proto_streaming_v1_streaming_proto_depIdxs = []int32{
	6,  // 0: sysarmor.streaming.v1.RecordContext.labels:type_name -> sysarmor.streaming.v1.RecordContext.LabelsEntry
	0,  // 1: sysarmor.streaming.v1.NormalizedTelemetry.context:type_name -> sysarmor.streaming.v1.RecordContext
	7,  // 2: sysarmor.streaming.v1.NormalizedTelemetry.event:type_name -> sysarmor.event.v1.CanonicalEvent
	8,  // 3: sysarmor.streaming.v1.NormalizedTelemetry.signal:type_name -> sysarmor.signal.v1.Signal
	9,  // 4: sysarmor.streaming.v1.DetectionPolicySnapshot.detection:type_name -> sysarmor.policy.v1.DetectionPolicy
	8,  // 5: sysarmor.streaming.v1.AnalysisArtifact.signal:type_name -> sysarmor.signal.v1.Signal
	10, // 6: sysarmor.streaming.v1.AnalysisArtifact.incident:type_name -> sysarmor.incident.v1.Incident
	1,  // 7: sysarmor.streaming.v1.LateTelemetry.telemetry:type_name -> sysarmor.streaming.v1.NormalizedTelemetry
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_packages_contracts_proto_streaming_v1_streaming_proto_init() }
func file_packages_contracts_proto_streaming_v1_streaming_proto_init() {
	if File_packages_contracts_proto_streaming_v1_streaming_proto != nil {
		return
	}
	file_packages_contracts_proto_streaming_v1_streaming_proto_msgTypes[1].OneofWrappers = []any{
		(*NormalizedTelemetry_Event)(nil),
		(*NormalizedTelemetry_Signal)(nil),
	}
	file_packages_contracts_proto_streaming_v1_streaming_proto_msgTypes[3].OneofWrappers = []any{
		(*AnalysisArtifact_Signal)(nil),
		(*AnalysisArtifact_Incident)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packages_contracts_proto_streaming_v1_streaming_proto_rawDesc), len(file_packages_contracts_proto_streaming_v1_streaming_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packages_contracts_proto_streaming_v1_streaming_proto_goTypes,
		DependencyIndexes: file_packages_contracts_proto_streaming_v1_streaming_proto_depIdxs,
		MessageInfos:      file_packages_contracts_proto_streaming_v1_streaming_proto_msgTypes,
	}.Build()
	File_packages_contracts_proto_streaming_v1_streaming_proto = out.File
	file_packages_contracts_proto_streaming_v1_streaming_proto_goTypes = nil
	file_packages_contracts_proto_streaming_v1_streaming_proto_depIdxs = nil
}
