// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: packages/contracts/proto/policy/v1/policy.proto

package policyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConvergeParams struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Mode                  string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	TopK                  uint32                 `protobuf:"varint,2,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	MaxPathHops           uint32                 `protobuf:"varint,3,opt,name=max_path_hops,json=maxPathHops,proto3" json:"max_path_hops,omitempty"`
	AdditiveRiskThreshold uint32                 `protobuf:"varint,4,opt,name=additive_risk_threshold,json=additiveRiskThreshold,proto3" json:"additive_risk_threshold,omitempty"`
	CrossLineage          bool                   `protobuf:"varint,5,opt,name=cross_lineage,json=crossLineage,proto3" json:"cross_lineage,omitempty"`
	StateRetentionNs      uint64                 `protobuf:"varint,6,opt,name=state_retention_ns,json=stateRetentionNs,proto3" json:"state_retention_ns,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ConvergeParams) Reset() {
	*x = ConvergeParams{}
	mi := &file_packages_contracts_proto_policy_v1_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvergeParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvergeParams) ProtoMessage() {}

func (x *ConvergeParams) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_proto_policy_v1_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvergeParams.ProtoReflect.Descriptor instead.
func (*ConvergeParams) Descriptor() ([]byte, []int) {
	return file_packages_contracts_proto_policy_v1_policy_proto_rawDescGZIP(), []int{0}
}

func (x *ConvergeParams) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *ConvergeParams) GetTopK() uint32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *ConvergeParams) GetMaxPathHops() uint32 {
	if x != nil {
		return x.MaxPathHops
	}
	return 0
}

func (x *ConvergeParams) GetAdditiveRiskThreshold() uint32 {
	if x != nil {
		return x.AdditiveRiskThreshold
	}
	return 0
}

func (x *ConvergeParams) GetCrossLineage() bool {
	if x != nil {
		return x.CrossLineage
	}
	return false
}

func (x *ConvergeParams) GetStateRetentionNs() uint64 {
	if x != nil {
		return x.StateRetentionNs
	}
	return 0
}

type RarityParams struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CmsWidth         uint32                 `protobuf:"varint,1,opt,name=cms_width,json=cmsWidth,proto3" json:"cms_width,omitempty"`
	CmsDepth         uint32                 `protobuf:"varint,2,opt,name=cms_depth,json=cmsDepth,proto3" json:"cms_depth,omitempty"`
	BaselineWindowNs uint64                 `protobuf:"varint,3,opt,name=baseline_window_ns,json=baselineWindowNs,proto3" json:"baseline_window_ns,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RarityParams) Reset() {
	*x = RarityParams{}
	mi := &file_packages_contracts_proto_policy_v1_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RarityParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RarityParams) ProtoMessage() {}

func (x *RarityParams) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_proto_policy_v1_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RarityParams.ProtoReflect.Descriptor instead.
func (*RarityParams) Descriptor() ([]byte, []int) {
	return file_packages_contracts_proto_policy_v1_policy_proto_rawDescGZIP(), []int{1}
}

func (x *RarityParams) GetCmsWidth() uint32 {
	if x != nil {
		return x.CmsWidth
	}
	return 0
}

func (x *RarityParams) GetCmsDepth() uint32 {
	if x != nil {
		return x.CmsDepth
	}
	return 0
}

func (x *RarityParams) GetBaselineWindowNs() uint64 {
	if x != nil {
		return x.BaselineWindowNs
	}
	return 0
}

type DetectionPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EndpointRules []string               `protobuf:"bytes,1,rep,name=endpoint_rules,json=endpointRules,proto3" json:"endpoint_rules,omitempty"`
	CloudRules    []string               `protobuf:"bytes,2,rep,name=cloud_rules,json=cloudRules,proto3" json:"cloud_rules,omitempty"`
	Converge      *ConvergeParams        `protobuf:"bytes,3,opt,name=converge,proto3" json:"converge,omitempty"`
	Rarity        *RarityParams          `protobuf:"bytes,4,opt,name=rarity,proto3" json:"rarity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectionPolicy) Reset() {
	*x = DetectionPolicy{}
	mi := &file_packages_contracts_proto_policy_v1_policy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectionPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectionPolicy) ProtoMessage() {}

func (x *DetectionPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_proto_policy_v1_policy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectionPolicy.ProtoReflect.Descriptor instead.
func (*DetectionPolicy) Descriptor() ([]byte, []int) {
	return file_packages_contracts_proto_policy_v1_policy_proto_rawDescGZIP(), []int{2}
}

func (x *DetectionPolicy) GetEndpointRules() []string {
	if x != nil {
		return x.EndpointRules
	}
	return nil
}

func (x *DetectionPolicy) GetCloudRules() []string {
	if x != nil {
		return x.CloudRules
	}
	return nil
}

func (x *DetectionPolicy) GetConverge() *ConvergeParams {
	if x != nil {
		return x.Converge
	}
	return nil
}

func (x *DetectionPolicy) GetRarity() *RarityParams {
	if x != nil {
		return x.Rarity
	}
	return nil
}

type PolicyEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Version       uint64                 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Detection     *DetectionPolicy       `protobuf:"bytes,4,opt,name=detection,proto3" json:"detection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyEnvelope) Reset() {
	*x = PolicyEnvelope{}
	mi := &file_packages_contracts_proto_policy_v1_policy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyEnvelope) ProtoMessage() {}

func (x *PolicyEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_proto_policy_v1_policy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyEnvelope.ProtoReflect.Descriptor instead.
func (*PolicyEnvelope) Descriptor() ([]byte, []int) {
	return file_packages_contracts_proto_policy_v1_policy_proto_rawDescGZIP(), []int{3}
}

func (x *PolicyEnvelope) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PolicyEnvelope) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PolicyEnvelope) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PolicyEnvelope) GetDetection() *DetectionPolicy {
	if x != nil {
		return x.Detection
	}
	return nil
}

var File_packages_contracts_proto_policy_v1_policy_proto protoreflect.FileDescriptor

const file_packages_contracts_proto_policy_v1_policy_proto_rawDesc = "" +
	"\n" +
	"/packages/contracts/proto/policy/v1/policy.proto\x12\x12sysarmor.policy.v1\"\xe8\x01\n" +
	"\x0eConvergeParams\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x13\n" +
	"\x05top_k\x18\x02 \x01(\rR\x04topK\x12\"\n" +
	"\rmax_path_hops\x18\x03 \x01(\rR\vmaxPathHops\x126\n" +
	"\x17additive_risk_threshold\x18\x04 \x01(\rR\x15additiveRiskThreshold\x12#\n" +
	"\rcross_lineage\x18\x05 \x01(\bR\fcrossLineage\x12,\n" +
	"\x12state_retention_ns\x18\x06 \x01(\x04R\x10stateRetentionNs\"v\n" +
	"\fRarityParams\x12\x1b\n" +
	"\tcms_width\x18\x01 \x01(\rR\bcmsWidth\x12\x1b\n" +
	"\tcms_depth\x18\x02 \x01(\rR\bcmsDepth\x12,\n" +
	"\x12baseline_window_ns\x18\x03 \x01(\x04R\x10baselineWindowNs\"\xd3\x01\n" +
	"\x0fDetectionPolicy\x12%\n" +
	"\x0eendpoint_rules\x18\x01 \x03(\tR\rendpointRules\x12\x1f\n" +
	"\vcloud_rules\x18\x02 \x03(\tR\n" +
	"cloudRules\x12>\n" +
	"\bconverge\x18\x03 \x01(\v2\".sysarmor.policy.v1.ConvergeParamsR\bconverge\x128\n" +
	"\x06rarity\x18\x04 \x01(\v2 .sysarmor.policy.v1.RarityParamsR\x06rarity\"\x91\x01\n" +
	"\x0ePolicyEnvelope\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x04R\aversion\x12A\n" +
	"\tdetection\x18\x04 \x01(\v2#.sysarmor.policy.v1.DetectionPolicyR\tdetectionBWZUgithub.com/sysarmor/sysarmor-next-project/packages/contracts/proto/policy/v1;policyv1b\x06proto3"

var (
	file_packages_contracts_proto_policy_v1_policy_proto_rawDescOnce sync.Once
	file_packages_contracts_proto_policy_v1_policy_proto_rawDescData []byte
)

func file_packages_contracts_proto_policy_v1_policy_proto_rawDescGZIP() []byte {
	file_packages_contracts_proto_policy_v1_policy_proto_rawDescOnce.Do(func() {
		file_packages_contracts_proto_policy_v1_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packages_contracts_proto_policy_v1_policy_proto_rawDesc), len(file_packages_contracts_proto_policy_v1_policy_proto_rawDesc)))
	})
	return file_packages_contracts_proto_policy_v1_policy_proto_rawDescData
}

var file_packages_contracts_proto_policy_v1_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_packages_contracts_proto_policy_v1_policy_proto_goTypes = []any{
	(*ConvergeParams)(nil),  // 0: sysarmor.policy.v1.ConvergeParams
	(*RarityParams)(nil),    // 1: sysarmor.policy.v1.RarityParams
	(*DetectionPolicy)(nil), // 2: sysarmor.policy.v1.DetectionPolicy
	(*PolicyEnvelope)(nil),  // 3: sysarmor.policy.v1.PolicyEnvelope
}
var file_packages_contracts_proto_policy_v1_policy_proto_depIdxs = []int32{
	0, // 0: sysarmor.policy.v1.DetectionPolicy.converge:type_name -> sysarmor.policy.v1.ConvergeParams
	1, // 1: sysarmor.policy.v1.DetectionPolicy.rarity:type_name -> sysarmor.policy.v1.RarityParams
	2, // 2: sysarmor.policy.v1.PolicyEnvelope.detection:type_name -> sysarmor.policy.v1.DetectionPolicy
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_packages_contracts_proto_policy_v1_policy_proto_init() }
func file_packages_contracts_proto_policy_v1_policy_proto_init() {
	if File_packages_contracts_proto_policy_v1_policy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packages_contracts_proto_policy_v1_policy_proto_rawDesc), len(file_packages_contracts_proto_policy_v1_policy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packages_contracts_proto_policy_v1_policy_proto_goTypes,
		DependencyIndexes: file_packages_contracts_proto_policy_v1_policy_proto_depIdxs,
		MessageInfos:      file_packages_contracts_proto_policy_v1_policy_proto_msgTypes,
	}.Build()
	File_packages_contracts_proto_policy_v1_policy_proto = out.File
	file_packages_contracts_proto_policy_v1_policy_proto_goTypes = nil
	file_packages_contracts_proto_policy_v1_policy_proto_depIdxs = nil
}
