// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: packages/contracts/proto/policy/v1/policy.proto

package policyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConvergeParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mode                  string `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	TopK                  uint32 `protobuf:"varint,2,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	MaxPathHops           uint32 `protobuf:"varint,3,opt,name=max_path_hops,json=maxPathHops,proto3" json:"max_path_hops,omitempty"`
	AdditiveRiskThreshold uint32 `protobuf:"varint,4,opt,name=additive_risk_threshold,json=additiveRiskThreshold,proto3" json:"additive_risk_threshold,omitempty"`
	CrossLineage          bool   `protobuf:"varint,5,opt,name=cross_lineage,json=crossLineage,proto3" json:"cross_lineage,omitempty"`
	StateRetentionNs      uint64 `protobuf:"varint,6,opt,name=state_retention_ns,json=stateRetentionNs,proto3" json:"state_retention_ns,omitempty"`
}

func (x *ConvergeParams) Reset() {
	*x = ConvergeParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packages_contracts_proto_policy_v1_policy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConvergeParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvergeParams) ProtoMessage() {}

func (x *ConvergeParams) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_proto_policy_v1_policy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvergeParams.ProtoReflect.Descriptor instead.
func (*ConvergeParams) Descriptor() ([]byte, []int) {
	return file_packages_contracts_proto_policy_v1_policy_proto_rawDescGZIP(), []int{0}
}

func (x *ConvergeParams) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *ConvergeParams) GetTopK() uint32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *ConvergeParams) GetMaxPathHops() uint32 {
	if x != nil {
		return x.MaxPathHops
	}
	return 0
}

func (x *ConvergeParams) GetAdditiveRiskThreshold() uint32 {
	if x != nil {
		return x.AdditiveRiskThreshold
	}
	return 0
}

func (x *ConvergeParams) GetCrossLineage() bool {
	if x != nil {
		return x.CrossLineage
	}
	return false
}

func (x *ConvergeParams) GetStateRetentionNs() uint64 {
	if x != nil {
		return x.StateRetentionNs
	}
	return 0
}

type RarityParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CmsWidth         uint32 `protobuf:"varint,1,opt,name=cms_width,json=cmsWidth,proto3" json:"cms_width,omitempty"`
	CmsDepth         uint32 `protobuf:"varint,2,opt,name=cms_depth,json=cmsDepth,proto3" json:"cms_depth,omitempty"`
	BaselineWindowNs uint64 `protobuf:"varint,3,opt,name=baseline_window_ns,json=baselineWindowNs,proto3" json:"baseline_window_ns,omitempty"`
}

func (x *RarityParams) Reset() {
	*x = RarityParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packages_contracts_proto_policy_v1_policy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RarityParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RarityParams) ProtoMessage() {}

func (x *RarityParams) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_proto_policy_v1_policy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RarityParams.ProtoReflect.Descriptor instead.
func (*RarityParams) Descriptor() ([]byte, []int) {
	return file_packages_contracts_proto_policy_v1_policy_proto_rawDescGZIP(), []int{1}
}

func (x *RarityParams) GetCmsWidth() uint32 {
	if x != nil {
		return x.CmsWidth
	}
	return 0
}

func (x *RarityParams) GetCmsDepth() uint32 {
	if x != nil {
		return x.CmsDepth
	}
	return 0
}

func (x *RarityParams) GetBaselineWindowNs() uint64 {
	if x != nil {
		return x.BaselineWindowNs
	}
	return 0
}

type DetectionPolicy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EndpointRules []string        `protobuf:"bytes,1,rep,name=endpoint_rules,json=endpointRules,proto3" json:"endpoint_rules,omitempty"`
	CloudRules    []string        `protobuf:"bytes,2,rep,name=cloud_rules,json=cloudRules,proto3" json:"cloud_rules,omitempty"`
	Converge      *ConvergeParams `protobuf:"bytes,3,opt,name=converge,proto3" json:"converge,omitempty"`
	Rarity        *RarityParams   `protobuf:"bytes,4,opt,name=rarity,proto3" json:"rarity,omitempty"`
	// Explicit allow-list of cloud Detectors. Empty means the platform default.
	Detectors []string `protobuf:"bytes,5,rep,name=detectors,proto3" json:"detectors,omitempty"`
}

func (x *DetectionPolicy) Reset() {
	*x = DetectionPolicy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packages_contracts_proto_policy_v1_policy_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DetectionPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectionPolicy) ProtoMessage() {}

func (x *DetectionPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_proto_policy_v1_policy_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectionPolicy.ProtoReflect.Descriptor instead.
func (*DetectionPolicy) Descriptor() ([]byte, []int) {
	return file_packages_contracts_proto_policy_v1_policy_proto_rawDescGZIP(), []int{2}
}

func (x *DetectionPolicy) GetEndpointRules() []string {
	if x != nil {
		return x.EndpointRules
	}
	return nil
}

func (x *DetectionPolicy) GetCloudRules() []string {
	if x != nil {
		return x.CloudRules
	}
	return nil
}

func (x *DetectionPolicy) GetConverge() *ConvergeParams {
	if x != nil {
		return x.Converge
	}
	return nil
}

func (x *DetectionPolicy) GetRarity() *RarityParams {
	if x != nil {
		return x.Rarity
	}
	return nil
}

func (x *DetectionPolicy) GetDetectors() []string {
	if x != nil {
		return x.Detectors
	}
	return nil
}

type PolicyEnvelope struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type      string           `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Version   uint64           `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Detection *DetectionPolicy `protobuf:"bytes,4,opt,name=detection,proto3" json:"detection,omitempty"`
}

func (x *PolicyEnvelope) Reset() {
	*x = PolicyEnvelope{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packages_contracts_proto_policy_v1_policy_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PolicyEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyEnvelope) ProtoMessage() {}

func (x *PolicyEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_proto_policy_v1_policy_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyEnvelope.ProtoReflect.Descriptor instead.
func (*PolicyEnvelope) Descriptor() ([]byte, []int) {
	return file_packages_contracts_proto_policy_v1_policy_proto_rawDescGZIP(), []int{3}
}

func (x *PolicyEnvelope) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PolicyEnvelope) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PolicyEnvelope) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PolicyEnvelope) GetDetection() *DetectionPolicy {
	if x != nil {
		return x.Detection
	}
	return nil
}

var File_packages_contracts_proto_policy_v1_policy_proto protoreflect.FileDescriptor

var file_packages_contracts_proto_policy_v1_policy_proto_rawDesc = []byte{
	0x0a, 0x2f, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6f, 0x6c, 0x69, 0x63,
	0x79, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x12, 0x73, 0x79, 0x73, 0x61, 0x72, 0x6d, 0x6f, 0x72, 0x2e, 0x70, 0x6f, 0x6c, 0x69,
	0x63, 0x79, 0x2e, 0x76, 0x31, 0x22, 0xe8, 0x01, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72,
	0x67, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x13, 0x0a, 0x05,
	0x74, 0x6f, 0x70, 0x5f, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x6f, 0x70,
	0x4b, 0x12, 0x22, 0x0a, 0x0d, 0x6d, 0x61, 0x78, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x5f, 0x68, 0x6f,
	0x70, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x6d, 0x61, 0x78, 0x50, 0x61, 0x74,
	0x68, 0x48, 0x6f, 0x70, 0x73, 0x12, 0x36, 0x0a, 0x17, 0x61, 0x64, 0x64, 0x69, 0x74, 0x69, 0x76,
	0x65, 0x5f, 0x72, 0x69, 0x73, 0x6b, 0x5f, 0x74, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x15, 0x61, 0x64, 0x64, 0x69, 0x74, 0x69, 0x76, 0x65,
	0x52, 0x69, 0x73, 0x6b, 0x54, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x12, 0x23, 0x0a,
	0x0d, 0x63, 0x72, 0x6f, 0x73, 0x73, 0x5f, 0x6c, 0x69, 0x6e, 0x65, 0x61, 0x67, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x63, 0x72, 0x6f, 0x73, 0x73, 0x4c, 0x69, 0x6e, 0x65, 0x61,
	0x67, 0x65, 0x12, 0x2c, 0x0a, 0x12, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x74, 0x65,
	0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x10,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x74, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x73,
	0x22, 0x76, 0x0a, 0x0c, 0x52, 0x61, 0x72, 0x69, 0x74, 0x79, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73,
	0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6d, 0x73, 0x5f, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x08, 0x63, 0x6d, 0x73, 0x57, 0x69, 0x64, 0x74, 0x68, 0x12, 0x1b, 0x0a,
	0x09, 0x63, 0x6d, 0x73, 0x5f, 0x64, 0x65, 0x70, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x08, 0x63, 0x6d, 0x73, 0x44, 0x65, 0x70, 0x74, 0x68, 0x12, 0x2c, 0x0a, 0x12, 0x62, 0x61,
	0x73, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x5f, 0x6e, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x10, 0x62, 0x61, 0x73, 0x65, 0x6c, 0x69, 0x6e, 0x65,
	0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x4e, 0x73, 0x22, 0xf1, 0x01, 0x0a, 0x0f, 0x44, 0x65, 0x74,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12, 0x25, 0x0a, 0x0e,
	0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x5f, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x75,
	0x6c, 0x65, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x5f, 0x72, 0x75, 0x6c,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x52,
	0x75, 0x6c, 0x65, 0x73, 0x12, 0x3e, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x67, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x73, 0x79, 0x73, 0x61, 0x72, 0x6d, 0x6f,
	0x72, 0x2e, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x76,
	0x65, 0x72, 0x67, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x76,
	0x65, 0x72, 0x67, 0x65, 0x12, 0x38, 0x0a, 0x06, 0x72, 0x61, 0x72, 0x69, 0x74, 0x79, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x73, 0x79, 0x73, 0x61, 0x72, 0x6d, 0x6f, 0x72, 0x2e,
	0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x61, 0x72, 0x69, 0x74, 0x79,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x06, 0x72, 0x61, 0x72, 0x69, 0x74, 0x79, 0x12, 0x1c,
	0x0a, 0x09, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x09, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x22, 0x91, 0x01, 0x0a,
	0x0e, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x41, 0x0a,
	0x09, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x23, 0x2e, 0x73, 0x79, 0x73, 0x61, 0x72, 0x6d, 0x6f, 0x72, 0x2e, 0x70, 0x6f, 0x6c, 0x69,
	0x63, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x50,
	0x6f, 0x6c, 0x69, 0x63, 0x79, 0x52, 0x09, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x42, 0x57, 0x5a, 0x55, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73,
	0x79, 0x73, 0x61, 0x72, 0x6d, 0x6f, 0x72, 0x2f, 0x73, 0x79, 0x73, 0x61, 0x72, 0x6d, 0x6f, 0x72,
	0x2d, 0x6e, 0x65, 0x78, 0x74, 0x2d, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x70, 0x61,
	0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x2f, 0x76, 0x31,
	0x3b, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_packages_contracts_proto_policy_v1_policy_proto_rawDescOnce sync.Once
	file_packages_contracts_proto_policy_v1_policy_proto_rawDescData = file_packages_contracts_proto_policy_v1_policy_proto_rawDesc
)

func file_packages_contracts_proto_policy_v1_policy_proto_rawDescGZIP() []byte {
	file_packages_contracts_proto_policy_v1_policy_proto_rawDescOnce.Do(func() {
		file_packages_contracts_proto_policy_v1_policy_proto_rawDescData = protoimpl.X.CompressGZIP(file_packages_contracts_proto_policy_v1_policy_proto_rawDescData)
	})
	return file_packages_contracts_proto_policy_v1_policy_proto_rawDescData
}

var file_packages_contracts_proto_policy_v1_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_packages_contracts_proto_policy_v1_policy_proto_goTypes = []interface{}{
	(*ConvergeParams)(nil),  // 0: sysarmor.policy.v1.ConvergeParams
	(*RarityParams)(nil),    // 1: sysarmor.policy.v1.RarityParams
	(*DetectionPolicy)(nil), // 2: sysarmor.policy.v1.DetectionPolicy
	(*PolicyEnvelope)(nil),  // 3: sysarmor.policy.v1.PolicyEnvelope
}
var file_packages_contracts_proto_policy_v1_policy_proto_depIdxs = []int32{
	0, // 0: sysarmor.policy.v1.DetectionPolicy.converge:type_name -> sysarmor.policy.v1.ConvergeParams
	1, // 1: sysarmor.policy.v1.DetectionPolicy.rarity:type_name -> sysarmor.policy.v1.RarityParams
	2, // 2: sysarmor.policy.v1.PolicyEnvelope.detection:type_name -> sysarmor.policy.v1.DetectionPolicy
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_packages_contracts_proto_policy_v1_policy_proto_init() }
func file_packages_contracts_proto_policy_v1_policy_proto_init() {
	if File_packages_contracts_proto_policy_v1_policy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_packages_contracts_proto_policy_v1_policy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConvergeParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packages_contracts_proto_policy_v1_policy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RarityParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packages_contracts_proto_policy_v1_policy_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DetectionPolicy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packages_contracts_proto_policy_v1_policy_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PolicyEnvelope); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_packages_contracts_proto_policy_v1_policy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packages_contracts_proto_policy_v1_policy_proto_goTypes,
		DependencyIndexes: file_packages_contracts_proto_policy_v1_policy_proto_depIdxs,
		MessageInfos:      file_packages_contracts_proto_policy_v1_policy_proto_msgTypes,
	}.Build()
	File_packages_contracts_proto_policy_v1_policy_proto = out.File
	file_packages_contracts_proto_policy_v1_policy_proto_rawDesc = nil
	file_packages_contracts_proto_policy_v1_policy_proto_goTypes = nil
	file_packages_contracts_proto_policy_v1_policy_proto_depIdxs = nil
}
