// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: packages/contracts/proto/incident/v1/incident.proto

package incidentv1

import (
	v1 "github.com/sysarmor/sysarmor-next-project/packages/contracts/proto/signal/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GraphNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Label         string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	Entities      []*v1.EntityRef        `protobuf:"bytes,4,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphNode) Reset() {
	*x = GraphNode{}
	mi := &file_packages_contracts_proto_incident_v1_incident_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphNode) ProtoMessage() {}

func (x *GraphNode) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_proto_incident_v1_incident_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphNode.ProtoReflect.Descriptor instead.
func (*GraphNode) Descriptor() ([]byte, []int) {
	return file_packages_contracts_proto_incident_v1_incident_proto_rawDescGZIP(), []int{0}
}

func (x *GraphNode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GraphNode) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *GraphNode) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *GraphNode) GetEntities() []*v1.EntityRef {
	if x != nil {
		return x.Entities
	}
	return nil
}

type GraphEdge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Kind          string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	EventRefs     []string               `protobuf:"bytes,5,rep,name=event_refs,json=eventRefs,proto3" json:"event_refs,omitempty"`
	Incomplete    bool                   `protobuf:"varint,6,opt,name=incomplete,proto3" json:"incomplete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphEdge) Reset() {
	*x = GraphEdge{}
	mi := &file_packages_contracts_proto_incident_v1_incident_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphEdge) ProtoMessage() {}

func (x *GraphEdge) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_proto_incident_v1_incident_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphEdge.ProtoReflect.Descriptor instead.
func (*GraphEdge) Descriptor() ([]byte, []int) {
	return file_packages_contracts_proto_incident_v1_incident_proto_rawDescGZIP(), []int{1}
}

func (x *GraphEdge) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GraphEdge) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *GraphEdge) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *GraphEdge) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *GraphEdge) GetEventRefs() []string {
	if x != nil {
		return x.EventRefs
	}
	return nil
}

func (x *GraphEdge) GetIncomplete() bool {
	if x != nil {
		return x.Incomplete
	}
	return false
}

type EvidenceSubgraph struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*GraphNode           `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges         []*GraphEdge           `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvidenceSubgraph) Reset() {
	*x = EvidenceSubgraph{}
	mi := &file_packages_contracts_proto_incident_v1_incident_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvidenceSubgraph) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvidenceSubgraph) ProtoMessage() {}

func (x *EvidenceSubgraph) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_proto_incident_v1_incident_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvidenceSubgraph.ProtoReflect.Descriptor instead.
func (*EvidenceSubgraph) Descriptor() ([]byte, []int) {
	return file_packages_contracts_proto_incident_v1_incident_proto_rawDescGZIP(), []int{2}
}

func (x *EvidenceSubgraph) GetNodes() []*GraphNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *EvidenceSubgraph) GetEdges() []*GraphEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

type ConvergeTrace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	SeedIds       []string               `protobuf:"bytes,2,rep,name=seed_ids,json=seedIds,proto3" json:"seed_ids,omitempty"`
	PathIds       []string               `protobuf:"bytes,3,rep,name=path_ids,json=pathIds,proto3" json:"path_ids,omitempty"`
	Score         float32                `protobuf:"fixed32,4,opt,name=score,proto3" json:"score,omitempty"`
	Controls      []string               `protobuf:"bytes,5,rep,name=controls,proto3" json:"controls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvergeTrace) Reset() {
	*x = ConvergeTrace{}
	mi := &file_packages_contracts_proto_incident_v1_incident_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvergeTrace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvergeTrace) ProtoMessage() {}

func (x *ConvergeTrace) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_proto_incident_v1_incident_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvergeTrace.ProtoReflect.Descriptor instead.
func (*ConvergeTrace) Descriptor() ([]byte, []int) {
	return file_packages_contracts_proto_incident_v1_incident_proto_rawDescGZIP(), []int{3}
}

func (x *ConvergeTrace) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ConvergeTrace) GetSeedIds() []string {
	if x != nil {
		return x.SeedIds
	}
	return nil
}

func (x *ConvergeTrace) GetPathIds() []string {
	if x != nil {
		return x.PathIds
	}
	return nil
}

func (x *ConvergeTrace) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ConvergeTrace) GetControls() []string {
	if x != nil {
		return x.Controls
	}
	return nil
}

type Incident struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Summary             string                 `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	Severity            uint32                 `protobuf:"varint,3,opt,name=severity,proto3" json:"severity,omitempty"`
	Mitre               []string               `protobuf:"bytes,4,rep,name=mitre,proto3" json:"mitre,omitempty"`
	LineageIds          []string               `protobuf:"bytes,5,rep,name=lineage_ids,json=lineageIds,proto3" json:"lineage_ids,omitempty"`
	Evidence            *EvidenceSubgraph      `protobuf:"bytes,7,opt,name=evidence,proto3" json:"evidence,omitempty"`
	Converge            *ConvergeTrace         `protobuf:"bytes,8,opt,name=converge,proto3" json:"converge,omitempty"`
	ContributingSignals []*v1.Signal           `protobuf:"bytes,9,rep,name=contributing_signals,json=contributingSignals,proto3" json:"contributing_signals,omitempty"`
	Labels              map[string]string      `protobuf:"bytes,10,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TenantId            string                 `protobuf:"bytes,11,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CorrelationKey      string                 `protobuf:"bytes,12,opt,name=correlation_key,json=correlationKey,proto3" json:"correlation_key,omitempty"`
	AnalysisVersion     string                 `protobuf:"bytes,13,opt,name=analysis_version,json=analysisVersion,proto3" json:"analysis_version,omitempty"`
	FirstObservedAt     string                 `protobuf:"bytes,14,opt,name=first_observed_at,json=firstObservedAt,proto3" json:"first_observed_at,omitempty"`
	LastObservedAt      string                 `protobuf:"bytes,15,opt,name=last_observed_at,json=lastObservedAt,proto3" json:"last_observed_at,omitempty"`
	ConclusionEntities  []string               `protobuf:"bytes,16,rep,name=conclusion_entities,json=conclusionEntities,proto3" json:"conclusion_entities,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Incident) Reset() {
	*x = Incident{}
	mi := &file_packages_contracts_proto_incident_v1_incident_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Incident) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Incident) ProtoMessage() {}

func (x *Incident) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_proto_incident_v1_incident_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Incident.ProtoReflect.Descriptor instead.
func (*Incident) Descriptor() ([]byte, []int) {
	return file_packages_contracts_proto_incident_v1_incident_proto_rawDescGZIP(), []int{4}
}

func (x *Incident) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Incident) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Incident) GetSeverity() uint32 {
	if x != nil {
		return x.Severity
	}
	return 0
}

func (x *Incident) GetMitre() []string {
	if x != nil {
		return x.Mitre
	}
	return nil
}

func (x *Incident) GetLineageIds() []string {
	if x != nil {
		return x.LineageIds
	}
	return nil
}

func (x *Incident) GetEvidence() *EvidenceSubgraph {
	if x != nil {
		return x.Evidence
	}
	return nil
}

func (x *Incident) GetConverge() *ConvergeTrace {
	if x != nil {
		return x.Converge
	}
	return nil
}

func (x *Incident) GetContributingSignals() []*v1.Signal {
	if x != nil {
		return x.ContributingSignals
	}
	return nil
}

func (x *Incident) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Incident) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Incident) GetCorrelationKey() string {
	if x != nil {
		return x.CorrelationKey
	}
	return ""
}

func (x *Incident) GetAnalysisVersion() string {
	if x != nil {
		return x.AnalysisVersion
	}
	return ""
}

func (x *Incident) GetFirstObservedAt() string {
	if x != nil {
		return x.FirstObservedAt
	}
	return ""
}

func (x *Incident) GetLastObservedAt() string {
	if x != nil {
		return x.LastObservedAt
	}
	return ""
}

func (x *Incident) GetConclusionEntities() []string {
	if x != nil {
		return x.ConclusionEntities
	}
	return nil
}

var File_packages_contracts_proto_incident_v1_incident_proto protoreflect.FileDescriptor

const file_packages_contracts_proto_incident_v1_incident_proto_rawDesc = "" +
	"\n" +
	"3packages/contracts/proto/incident/v1/incident.proto\x12\x14sysarmor.incident.v1\x1a/packages/contracts/proto/signal/v1/signal.proto\"\x80\x01\n" +
	"\tGraphNode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x129\n" +
	"\bentities\x18\x04 \x03(\v2\x1d.sysarmor.signal.v1.EntityRefR\bentities\"\x92\x01\n" +
	"\tGraphEdge\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\x12\x1d\n" +
	"\n" +
	"event_refs\x18\x05 \x03(\tR\teventRefs\x12\x1e\n" +
	"\n" +
	"incomplete\x18\x06 \x01(\bR\n" +
	"incomplete\"\x80\x01\n" +
	"\x10EvidenceSubgraph\x125\n" +
	"\x05nodes\x18\x01 \x03(\v2\x1f.sysarmor.incident.v1.GraphNodeR\x05nodes\x125\n" +
	"\x05edges\x18\x02 \x03(\v2\x1f.sysarmor.incident.v1.GraphEdgeR\x05edges\"\x8f\x01\n" +
	"\rConvergeTrace\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x19\n" +
	"\bseed_ids\x18\x02 \x03(\tR\aseedIds\x12\x19\n" +
	"\bpath_ids\x18\x03 \x03(\tR\apathIds\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x02R\x05score\x12\x1a\n" +
	"\bcontrols\x18\x05 \x03(\tR\bcontrols\"\xe3\x05\n" +
	"\bIncident\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x12\x1a\n" +
	"\bseverity\x18\x03 \x01(\rR\bseverity\x12\x14\n" +
	"\x05mitre\x18\x04 \x03(\tR\x05mitre\x12\x1f\n" +
	"\vlineage_ids\x18\x05 \x03(\tR\n" +
	"lineageIds\x12B\n" +
	"\bevidence\x18\a \x01(\v2&.sysarmor.incident.v1.EvidenceSubgraphR\bevidence\x12?\n" +
	"\bconverge\x18\b \x01(\v2#.sysarmor.incident.v1.ConvergeTraceR\bconverge\x12M\n" +
	"\x14contributing_signals\x18\t \x03(\v2\x1a.sysarmor.signal.v1.SignalR\x13contributingSignals\x12B\n" +
	"\x06labels\x18\n" +
	" \x03(\v2*.sysarmor.incident.v1.Incident.LabelsEntryR\x06labels\x12\x1b\n" +
	"\ttenant_id\x18\v \x01(\tR\btenantId\x12'\n" +
	"\x0fcorrelation_key\x18\f \x01(\tR\x0ecorrelationKey\x12)\n" +
	"\x10analysis_version\x18\r \x01(\tR\x0fanalysisVersion\x12*\n" +
	"\x11first_observed_at\x18\x0e \x01(\tR\x0ffirstObservedAt\x12(\n" +
	"\x10last_observed_at\x18\x0f \x01(\tR\x0elastObservedAt\x12/\n" +
	"\x13conclusion_entities\x18\x10 \x03(\tR\x12conclusionEntities\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x06\x10\aR\tterminalsB[ZYgithub.com/sysarmor/sysarmor-next-project/packages/contracts/proto/incident/v1;incidentv1b\x06proto3"

var (
	file_packages_contracts_proto_incident_v1_incident_proto_rawDescOnce sync.Once
	file_packages_contracts_proto_incident_v1_incident_proto_rawDescData []byte
)

func file_packages_contracts_proto_incident_v1_incident_proto_rawDescGZIP() []byte {
	file_packages_contracts_proto_incident_v1_incident_proto_rawDescOnce.Do(func() {
		file_packages_contracts_proto_incident_v1_incident_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packages_contracts_proto_incident_v1_incident_proto_rawDesc), len(file_packages_contracts_proto_incident_v1_incident_proto_rawDesc)))
	})
	return file_packages_contracts_proto_incident_v1_incident_proto_rawDescData
}

var file_packages_contracts_proto_incident_v1_incident_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_packages_contracts_proto_incident_v1_incident_proto_goTypes = []any{
	(*GraphNode)(nil),        // 0: sysarmor.incident.v1.GraphNode
	(*GraphEdge)(nil),        // 1: sysarmor.incident.v1.GraphEdge
	(*EvidenceSubgraph)(nil), // 2: sysarmor.incident.v1.EvidenceSubgraph
	(*ConvergeTrace)(nil),    // 3: sysarmor.incident.v1.ConvergeTrace
	(*Incident)(nil),         // 4: sysarmor.incident.v1.Incident
	nil,                      // 5: sysarmor.incident.v1.Incident.LabelsEntry
	(*v1.EntityRef)(nil),     // 6: sysarmor.signal.v1.EntityRef
	(*v1.Signal)(nil),        // 7: sysarmor.signal.v1.Signal
}
var file_packages_contracts_proto_incident_v1_incident_proto_depIdxs = []int32{
	6, // 0: sysarmor.incident.v1.GraphNode.entities:type_name -> sysarmor.signal.v1.EntityRef
	0, // 1: sysarmor.incident.v1.EvidenceSubgraph.nodes:type_name -> sysarmor.incident.v1.GraphNode
	1, // 2: sysarmor.incident.v1.EvidenceSubgraph.edges:type_name -> sysarmor.incident.v1.GraphEdge
	2, // 3: sysarmor.incident.v1.Incident.evidence:type_name -> sysarmor.incident.v1.EvidenceSubgraph
	3, // 4: sysarmor.incident.v1.Incident.converge:type_name -> sysarmor.incident.v1.ConvergeTrace
	7, // 5: sysarmor.incident.v1.Incident.contributing_signals:type_name -> sysarmor.signal.v1.Signal
	5, // 6: sysarmor.incident.v1.Incident.labels:type_name -> sysarmor.incident.v1.Incident.LabelsEntry
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_packages_contracts_proto_incident_v1_incident_proto_init() }
func file_packages_contracts_proto_incident_v1_incident_proto_init() {
	if File_packages_contracts_proto_incident_v1_incident_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packages_contracts_proto_incident_v1_incident_proto_rawDesc), len(file_packages_contracts_proto_incident_v1_incident_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packages_contracts_proto_incident_v1_incident_proto_goTypes,
		DependencyIndexes: file_packages_contracts_proto_incident_v1_incident_proto_depIdxs,
		MessageInfos:      file_packages_contracts_proto_incident_v1_incident_proto_msgTypes,
	}.Build()
	File_packages_contracts_proto_incident_v1_incident_proto = out.File
	file_packages_contracts_proto_incident_v1_incident_proto_goTypes = nil
	file_packages_contracts_proto_incident_v1_incident_proto_depIdxs = nil
}
