// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: packages/contracts/proto/event/v1/event.proto

package eventv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessRef struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	StableId              string                 `protobuf:"bytes,1,opt,name=stable_id,json=stableId,proto3" json:"stable_id,omitempty"`
	Pid                   uint32                 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Binary                string                 `protobuf:"bytes,3,opt,name=binary,proto3" json:"binary,omitempty"`
	Argv                  []string               `protobuf:"bytes,4,rep,name=argv,proto3" json:"argv,omitempty"`
	Uid                   uint32                 `protobuf:"varint,5,opt,name=uid,proto3" json:"uid,omitempty"`
	StartTimeNs           uint64                 `protobuf:"varint,6,opt,name=start_time_ns,json=startTimeNs,proto3" json:"start_time_ns,omitempty"`
	ArgvBoundariesTrusted bool                   `protobuf:"varint,7,opt,name=argv_boundaries_trusted,json=argvBoundariesTrusted,proto3" json:"argv_boundaries_trusted,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ProcessRef) Reset() {
	*x = ProcessRef{}
	mi := &file_packages_contracts_proto_event_v1_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessRef) ProtoMessage() {}

func (x *ProcessRef) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_proto_event_v1_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessRef.ProtoReflect.Descriptor instead.
func (*ProcessRef) Descriptor() ([]byte, []int) {
	return file_packages_contracts_proto_event_v1_event_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessRef) GetStableId() string {
	if x != nil {
		return x.StableId
	}
	return ""
}

func (x *ProcessRef) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessRef) GetBinary() string {
	if x != nil {
		return x.Binary
	}
	return ""
}

func (x *ProcessRef) GetArgv() []string {
	if x != nil {
		return x.Argv
	}
	return nil
}

func (x *ProcessRef) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ProcessRef) GetStartTimeNs() uint64 {
	if x != nil {
		return x.StartTimeNs
	}
	return 0
}

func (x *ProcessRef) GetArgvBoundariesTrusted() bool {
	if x != nil {
		return x.ArgvBoundariesTrusted
	}
	return false
}

type ObjectRef struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Kind               string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	FilePath           string                 `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	SocketAddr         string                 `protobuf:"bytes,3,opt,name=socket_addr,json=socketAddr,proto3" json:"socket_addr,omitempty"`
	TargetProcStableId string                 `protobuf:"bytes,4,opt,name=target_proc_stable_id,json=targetProcStableId,proto3" json:"target_proc_stable_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ObjectRef) Reset() {
	*x = ObjectRef{}
	mi := &file_packages_contracts_proto_event_v1_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectRef) ProtoMessage() {}

func (x *ObjectRef) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_proto_event_v1_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectRef.ProtoReflect.Descriptor instead.
func (*ObjectRef) Descriptor() ([]byte, []int) {
	return file_packages_contracts_proto_event_v1_event_proto_rawDescGZIP(), []int{1}
}

func (x *ObjectRef) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ObjectRef) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *ObjectRef) GetSocketAddr() string {
	if x != nil {
		return x.SocketAddr
	}
	return ""
}

func (x *ObjectRef) GetTargetProcStableId() string {
	if x != nil {
		return x.TargetProcStableId
	}
	return ""
}

type RuntimeScope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Selector      string                 `protobuf:"bytes,2,opt,name=selector,proto3" json:"selector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeScope) Reset() {
	*x = RuntimeScope{}
	mi := &file_packages_contracts_proto_event_v1_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeScope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeScope) ProtoMessage() {}

func (x *RuntimeScope) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_proto_event_v1_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeScope.ProtoReflect.Descriptor instead.
func (*RuntimeScope) Descriptor() ([]byte, []int) {
	return file_packages_contracts_proto_event_v1_event_proto_rawDescGZIP(), []int{2}
}

func (x *RuntimeScope) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RuntimeScope) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

type CanonicalEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Seq            uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	AgentId        string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	HostId         string                 `protobuf:"bytes,4,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	MonoNs         uint64                 `protobuf:"varint,6,opt,name=mono_ns,json=monoNs,proto3" json:"mono_ns,omitempty"`
	SubjectProc    *ProcessRef            `protobuf:"bytes,8,opt,name=subject_proc,json=subjectProc,proto3" json:"subject_proc,omitempty"`
	Object         *ObjectRef             `protobuf:"bytes,9,opt,name=object,proto3" json:"object,omitempty"`
	ParentStableId string                 `protobuf:"bytes,10,opt,name=parent_stable_id,json=parentStableId,proto3" json:"parent_stable_id,omitempty"`
	LineageId      string                 `protobuf:"bytes,11,opt,name=lineage_id,json=lineageId,proto3" json:"lineage_id,omitempty"`
	RawRef         string                 `protobuf:"bytes,12,opt,name=raw_ref,json=rawRef,proto3" json:"raw_ref,omitempty"`
	TenantId       string                 `protobuf:"bytes,13,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Scope          *RuntimeScope          `protobuf:"bytes,14,opt,name=scope,proto3" json:"scope,omitempty"`
	ContainerId    string                 `protobuf:"bytes,15,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Cgroup         string                 `protobuf:"bytes,16,opt,name=cgroup,proto3" json:"cgroup,omitempty"`
	Namespace      string                 `protobuf:"bytes,17,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Pod            string                 `protobuf:"bytes,18,opt,name=pod,proto3" json:"pod,omitempty"`
	OccurredAtNs   uint64                 `protobuf:"varint,19,opt,name=occurred_at_ns,json=occurredAtNs,proto3" json:"occurred_at_ns,omitempty"`
	Behavior       string                 `protobuf:"bytes,20,opt,name=behavior,proto3" json:"behavior,omitempty"`
	Labels         map[string]string      `protobuf:"bytes,21,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IdentityStatus string                 `protobuf:"bytes,22,opt,name=identity_status,json=identityStatus,proto3" json:"identity_status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CanonicalEvent) Reset() {
	*x = CanonicalEvent{}
	mi := &file_packages_contracts_proto_event_v1_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanonicalEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanonicalEvent) ProtoMessage() {}

func (x *CanonicalEvent) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_proto_event_v1_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanonicalEvent.ProtoReflect.Descriptor instead.
func (*CanonicalEvent) Descriptor() ([]byte, []int) {
	return file_packages_contracts_proto_event_v1_event_proto_rawDescGZIP(), []int{3}
}

func (x *CanonicalEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CanonicalEvent) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *CanonicalEvent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CanonicalEvent) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *CanonicalEvent) GetMonoNs() uint64 {
	if x != nil {
		return x.MonoNs
	}
	return 0
}

func (x *CanonicalEvent) GetSubjectProc() *ProcessRef {
	if x != nil {
		return x.SubjectProc
	}
	return nil
}

func (x *CanonicalEvent) GetObject() *ObjectRef {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *CanonicalEvent) GetParentStableId() string {
	if x != nil {
		return x.ParentStableId
	}
	return ""
}

func (x *CanonicalEvent) GetLineageId() string {
	if x != nil {
		return x.LineageId
	}
	return ""
}

func (x *CanonicalEvent) GetRawRef() string {
	if x != nil {
		return x.RawRef
	}
	return ""
}

func (x *CanonicalEvent) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CanonicalEvent) GetScope() *RuntimeScope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *CanonicalEvent) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *CanonicalEvent) GetCgroup() string {
	if x != nil {
		return x.Cgroup
	}
	return ""
}

func (x *CanonicalEvent) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *CanonicalEvent) GetPod() string {
	if x != nil {
		return x.Pod
	}
	return ""
}

func (x *CanonicalEvent) GetOccurredAtNs() uint64 {
	if x != nil {
		return x.OccurredAtNs
	}
	return 0
}

func (x *CanonicalEvent) GetBehavior() string {
	if x != nil {
		return x.Behavior
	}
	return ""
}

func (x *CanonicalEvent) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *CanonicalEvent) GetIdentityStatus() string {
	if x != nil {
		return x.IdentityStatus
	}
	return ""
}

var File_packages_contracts_proto_event_v1_event_proto protoreflect.FileDescriptor

const file_packages_contracts_proto_event_v1_event_proto_rawDesc = "" +
	"\n" +
	"-packages/contracts/proto/event/v1/event.proto\x12\x11sysarmor.event.v1\"\xd5\x01\n" +
	"\n" +
	"ProcessRef\x12\x1b\n" +
	"\tstable_id\x18\x01 \x01(\tR\bstableId\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\rR\x03pid\x12\x16\n" +
	"\x06binary\x18\x03 \x01(\tR\x06binary\x12\x12\n" +
	"\x04argv\x18\x04 \x03(\tR\x04argv\x12\x10\n" +
	"\x03uid\x18\x05 \x01(\rR\x03uid\x12\"\n" +
	"\rstart_time_ns\x18\x06 \x01(\x04R\vstartTimeNs\x126\n" +
	"\x17argv_boundaries_trusted\x18\a \x01(\bR\x15argvBoundariesTrusted\"\x90\x01\n" +
	"\tObjectRef\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1b\n" +
	"\tfile_path\x18\x02 \x01(\tR\bfilePath\x12\x1f\n" +
	"\vsocket_addr\x18\x03 \x01(\tR\n" +
	"socketAddr\x121\n" +
	"\x15target_proc_stable_id\x18\x04 \x01(\tR\x12targetProcStableId\">\n" +
	"\fRuntimeScope\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1a\n" +
	"\bselector\x18\x02 \x01(\tR\bselector\"\x9b\x06\n" +
	"\x0eCanonicalEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12\x17\n" +
	"\ahost_id\x18\x04 \x01(\tR\x06hostId\x12\x17\n" +
	"\amono_ns\x18\x06 \x01(\x04R\x06monoNs\x12@\n" +
	"\fsubject_proc\x18\b \x01(\v2\x1d.sysarmor.event.v1.ProcessRefR\vsubjectProc\x124\n" +
	"\x06object\x18\t \x01(\v2\x1c.sysarmor.event.v1.ObjectRefR\x06object\x12(\n" +
	"\x10parent_stable_id\x18\n" +
	" \x01(\tR\x0eparentStableId\x12\x1d\n" +
	"\n" +
	"lineage_id\x18\v \x01(\tR\tlineageId\x12\x17\n" +
	"\araw_ref\x18\f \x01(\tR\x06rawRef\x12\x1b\n" +
	"\ttenant_id\x18\r \x01(\tR\btenantId\x125\n" +
	"\x05scope\x18\x0e \x01(\v2\x1f.sysarmor.event.v1.RuntimeScopeR\x05scope\x12!\n" +
	"\fcontainer_id\x18\x0f \x01(\tR\vcontainerId\x12\x16\n" +
	"\x06cgroup\x18\x10 \x01(\tR\x06cgroup\x12\x1c\n" +
	"\tnamespace\x18\x11 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03pod\x18\x12 \x01(\tR\x03pod\x12$\n" +
	"\x0eoccurred_at_ns\x18\x13 \x01(\x04R\foccurredAtNs\x12\x1a\n" +
	"\bbehavior\x18\x14 \x01(\tR\bbehavior\x12E\n" +
	"\x06labels\x18\x15 \x03(\v2-.sysarmor.event.v1.CanonicalEvent.LabelsEntryR\x06labels\x12'\n" +
	"\x0fidentity_status\x18\x16 \x01(\tR\x0eidentityStatus\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x05\x10\x06J\x04\b\a\x10\bR\bscenarioBUZSgithub.com/sysarmor/sysarmor-next-project/packages/contracts/proto/event/v1;eventv1b\x06proto3"

var (
	file_packages_contracts_proto_event_v1_event_proto_rawDescOnce sync.Once
	file_packages_contracts_proto_event_v1_event_proto_rawDescData []byte
)

func file_packages_contracts_proto_event_v1_event_proto_rawDescGZIP() []byte {
	file_packages_contracts_proto_event_v1_event_proto_rawDescOnce.Do(func() {
		file_packages_contracts_proto_event_v1_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packages_contracts_proto_event_v1_event_proto_rawDesc), len(file_packages_contracts_proto_event_v1_event_proto_rawDesc)))
	})
	return file_packages_contracts_proto_event_v1_event_proto_rawDescData
}

var file_packages_contracts_proto_event_v1_event_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_packages_contracts_proto_event_v1_event_proto_goTypes = []any{
	(*ProcessRef)(nil),     // 0: sysarmor.event.v1.ProcessRef
	(*ObjectRef)(nil),      // 1: sysarmor.event.v1.ObjectRef
	(*RuntimeScope)(nil),   // 2: sysarmor.event.v1.RuntimeScope
	(*CanonicalEvent)(nil), // 3: sysarmor.event.v1.CanonicalEvent
	nil,                    // 4: sysarmor.event.v1.CanonicalEvent.LabelsEntry
}
var file_packages_contracts_proto_event_v1_event_proto_depIdxs = []int32{
	0, // 0: sysarmor.event.v1.CanonicalEvent.subject_proc:type_name -> sysarmor.event.v1.ProcessRef
	1, // 1: sysarmor.event.v1.CanonicalEvent.object:type_name -> sysarmor.event.v1.ObjectRef
	2, // 2: sysarmor.event.v1.CanonicalEvent.scope:type_name -> sysarmor.event.v1.RuntimeScope
	4, // 3: sysarmor.event.v1.CanonicalEvent.labels:type_name -> sysarmor.event.v1.CanonicalEvent.LabelsEntry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_packages_contracts_proto_event_v1_event_proto_init() }
func file_packages_contracts_proto_event_v1_event_proto_init() {
	if File_packages_contracts_proto_event_v1_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packages_contracts_proto_event_v1_event_proto_rawDesc), len(file_packages_contracts_proto_event_v1_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packages_contracts_proto_event_v1_event_proto_goTypes,
		DependencyIndexes: file_packages_contracts_proto_event_v1_event_proto_depIdxs,
		MessageInfos:      file_packages_contracts_proto_event_v1_event_proto_msgTypes,
	}.Build()
	File_packages_contracts_proto_event_v1_event_proto = out.File
	file_packages_contracts_proto_event_v1_event_proto_goTypes = nil
	file_packages_contracts_proto_event_v1_event_proto_depIdxs = nil
}
