# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: packages/contracts/proto/sensor/v1/sensor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/packages/contracts/proto/sensor/v1/sensor.proto\x12\x12sysarmor.sensor.v1\"\xd1\x01\n\nRawProcess\x12\x0b\n\x03pid\x18\x01 \x01(\r\x12\x0c\n\x04ppid\x18\x02 \x01(\r\x12\x0e\n\x06\x62inary\x18\x03 \x01(\t\x12\x0c\n\x04\x61rgv\x18\x04 \x03(\t\x12\x0b\n\x03uid\x18\x05 \x01(\r\x12\x15\n\rstart_time_ns\x18\x06 \x01(\x04\x12\x0e\n\x06\x63group\x18\x07 \x01(\t\x12\x16\n\x0esensor_exec_id\x18\x08 \x01(\t\x12\x1d\n\x15sensor_parent_exec_id\x18\t \x01(\t\x12\x1f\n\x17\x61rgv_boundaries_trusted\x18\n \x01(\x08\":\n\tRawObject\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0b\n\x03\x64st\x18\x02 \x01(\t\x12\x12\n\ntarget_pid\x18\x03 \x01(\r\"\xba\x01\n\x0bSensorEvent\x12\x0f\n\x07mono_ns\x18\x01 \x01(\x04\x12,\n\x04proc\x18\x03 \x01(\x0b\x32\x1e.sysarmor.sensor.v1.RawProcess\x12-\n\x06object\x18\x04 \x01(\x0b\x32\x1d.sysarmor.sensor.v1.RawObject\x12\x14\n\x0c\x63ontainer_id\x18\x05 \x01(\t\x12\x0f\n\x07raw_ref\x18\x06 \x01(\t\x12\x10\n\x08\x62\x65havior\x18\x07 \x01(\tJ\x04\x08\x02\x10\x03\">\n\x0cSensorHealth\x12\x16\n\x0e\x64ropped_events\x18\x01 \x01(\x04\x12\x16\n\x0e\x65vents_per_sec\x18\x02 \x01(\x01\x42WZUgithub.com/sysarmor/sysarmor-next-project/packages/contracts/proto/sensor/v1;sensorv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'packages.contracts.proto.sensor.v1.sensor_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZUgithub.com/sysarmor/sysarmor-next-project/packages/contracts/proto/sensor/v1;sensorv1'
  _globals['_RAWPROCESS']._serialized_start=72
  _globals['_RAWPROCESS']._serialized_end=281
  _globals['_RAWOBJECT']._serialized_start=283
  _globals['_RAWOBJECT']._serialized_end=341
  _globals['_SENSOREVENT']._serialized_start=344
  _globals['_SENSOREVENT']._serialized_end=530
  _globals['_SENSORHEALTH']._serialized_start=532
  _globals['_SENSORHEALTH']._serialized_end=594
# @@protoc_insertion_point(module_scope)
