# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: packages/contracts/proto/event/v1/event.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-packages/contracts/proto/event/v1/event.proto\x12\x11sysarmor.event.v1\"\x8f\x01\n\nProcessRef\x12\x11\n\tstable_id\x18\x01 \x01(\t\x12\x0b\n\x03pid\x18\x02 \x01(\r\x12\x0e\n\x06\x62inary\x18\x03 \x01(\t\x12\x0c\n\x04\x61rgv\x18\x04 \x03(\t\x12\x0b\n\x03uid\x18\x05 \x01(\r\x12\x15\n\rstart_time_ns\x18\x06 \x01(\x04\x12\x1f\n\x17\x61rgv_boundaries_trusted\x18\x07 \x01(\x08\"`\n\tObjectRef\x12\x0c\n\x04kind\x18\x01 \x01(\t\x12\x11\n\tfile_path\x18\x02 \x01(\t\x12\x13\n\x0bsocket_addr\x18\x03 \x01(\t\x12\x1d\n\x15target_proc_stable_id\x18\x04 \x01(\t\".\n\x0cRuntimeScope\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x10\n\x08selector\x18\x02 \x01(\t\"\xcf\x04\n\x0e\x43\x61nonicalEvent\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03seq\x18\x02 \x01(\x04\x12\x10\n\x08\x61gent_id\x18\x03 \x01(\t\x12\x0f\n\x07host_id\x18\x04 \x01(\t\x12\x0f\n\x07mono_ns\x18\x06 \x01(\x04\x12\x33\n\x0csubject_proc\x18\x08 \x01(\x0b\x32\x1d.sysarmor.event.v1.ProcessRef\x12,\n\x06object\x18\t \x01(\x0b\x32\x1c.sysarmor.event.v1.ObjectRef\x12\x18\n\x10parent_stable_id\x18\n \x01(\t\x12\x12\n\nlineage_id\x18\x0b \x01(\t\x12\x0f\n\x07raw_ref\x18\x0c \x01(\t\x12\x11\n\ttenant_id\x18\r \x01(\t\x12.\n\x05scope\x18\x0e \x01(\x0b\x32\x1f.sysarmor.event.v1.RuntimeScope\x12\x14\n\x0c\x63ontainer_id\x18\x0f \x01(\t\x12\x0e\n\x06\x63group\x18\x10 \x01(\t\x12\x11\n\tnamespace\x18\x11 \x01(\t\x12\x0b\n\x03pod\x18\x12 \x01(\t\x12\x16\n\x0eoccurred_at_ns\x18\x13 \x01(\x04\x12\x10\n\x08\x62\x65havior\x18\x14 \x01(\t\x12=\n\x06labels\x18\x15 \x03(\x0b\x32-.sysarmor.event.v1.CanonicalEvent.LabelsEntry\x12\x17\n\x0fidentity_status\x18\x16 \x01(\t\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01J\x04\x08\x05\x10\x06J\x04\x08\x07\x10\x08R\x08scenarioBUZSgithub.com/sysarmor/sysarmor-next-project/packages/contracts/proto/event/v1;eventv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'packages.contracts.proto.event.v1.event_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZSgithub.com/sysarmor/sysarmor-next-project/packages/contracts/proto/event/v1;eventv1'
  _CANONICALEVENT_LABELSENTRY._options = None
  _CANONICALEVENT_LABELSENTRY._serialized_options = b'8\001'
  _globals['_PROCESSREF']._serialized_start=69
  _globals['_PROCESSREF']._serialized_end=212
  _globals['_OBJECTREF']._serialized_start=214
  _globals['_OBJECTREF']._serialized_end=310
  _globals['_RUNTIMESCOPE']._serialized_start=312
  _globals['_RUNTIMESCOPE']._serialized_end=358
  _globals['_CANONICALEVENT']._serialized_start=361
  _globals['_CANONICALEVENT']._serialized_end=952
  _globals['_CANONICALEVENT_LABELSENTRY']._serialized_start=885
  _globals['_CANONICALEVENT_LABELSENTRY']._serialized_end=930
# @@protoc_insertion_point(module_scope)
